# Generated by Django 2.0.5 on 2018-07-09 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('nfc_tag_list', models.TextField()),
                ('nfc_tag_list_group', models.TextField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoorNfcTagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_name', models.CharField(max_length=15)),
                ('nfc_tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NfcDACPhase1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userKeys', models.TextField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NfcDACPhase2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userKeys', models.TextField(max_length=32)),
                ('keyHash', models.TextField(max_length=256)),
                ('TDAT2', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='NfcDACPhase3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userKeys', models.TextField(max_length=32)),
                ('aesEncryptedNfcPw', models.TextField(max_length=256)),
                ('aesSalt', models.TextField(max_length=96)),
                ('TDAT3', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='NfcDoor',
            fields=[
                ('nameOfDoor', models.CharField(max_length=255)),
                ('doorUUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NfcDoorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfDoorGroup', models.CharField(max_length=255)),
                ('listOfDoors', models.ManyToManyField(related_name='listOfDoors_NfcDoorGroup', to='profiles_api.NfcDoor')),
            ],
        ),
        migrations.CreateModel(
            name='NfcKey',
            fields=[
                ('keyName', models.CharField(max_length=255)),
                ('keyUUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('keyUTID', models.TextField(default=uuid.uuid4, max_length=64)),
                ('AESEncryptKey', models.TextField(default='HtnawdDNEU2s0qPBfiaOiJaxhWhdgs2I', max_length=32)),
                ('accesTrue', models.TextField(default='5bGIEKaYByObFLyDeKiTGJlpN1QtrD6knlt0u6l8kK0KJkCfQjla1yt0qZxTzCZThkN3pNMe2l440YmsVCqktDGmLkpUm8ldvkl4rcoeQu6GgIBJ0JuC7s1pOXPQUwOyVEGoIQdjs0SN8mqo1DGRRKuPAjluiZmuJzIUOxMfgyCpMEFY5GOxaFhYTudJcQaanecRoUcuvMCrZfimLm1EHckWs9z7O5XZk9utflM9hSANPUmVWdgQjeFX3VHuQcRG', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='NfcListOfUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('TDAT', models.TextField(default='oljcjn4cEZ51qO88DNaRFYKYEdDNA8eKnIHB9o5xB6VRfgb8ZZ0Z50nDLbPyHWE2A1cBbFDoEzJYrTdeeZbNXV5FrZVJ8xOyMLVaisxFaJfGZT221dv6b7SatPGXkvecLLiJjLbgbJxatuYdLgxT7xIhCXDW2r59iBZ3CcQbYAMa6B6dKG4o5iuQmKbLLBeVcudsIabRTm8Wfa38tFsnWrz8lkY9bEciLmvSnrdgdIQe8hNRy5NLqEQR0dTsz6v0', max_length=256)),
                ('accessingUUID', models.UUIDField(default=uuid.uuid4)),
                ('accesingUDID', models.UUIDField(default=uuid.uuid4)),
                ('encryptionKey', models.TextField(default='L5EOsj66oxlrmdeJqCxAboWw50JnKqD2', max_length=32)),
                ('encryptionSalt', models.TextField(default='Tj2WNZFQikWtW2Q4Xqk5rmvot08xPqKi', max_length=32)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('listOfDoorGroups', models.ManyToManyField(related_name='DoorGroup_NfcListOfUsers', to='profiles_api.NfcDoorGroup')),
                ('listOfDoors', models.ManyToManyField(related_name='ListOfDoors_NfcListOfUsers', to='profiles_api.NfcDoor')),
                ('userKeys', models.ManyToManyField(related_name='ListOfKeys_NfcListOfUsers', to='profiles_api.NfcKey')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
