# Generated by Django 2.0.5 on 2018-07-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='47xVkcprye38JJ0HEVKncyRf8A2BbNEe', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='ZIzj8UegrgwAfWGWsEIUYpYkXknjTd6J4rK9gRtXoMAQrdLBnLGbumwhT363BL3QePTd1IiTXAJHJ58CLT0gsOUydgacYMNW876KZW5lVY1QuL4PJgSAdHCWGDjDDds48dMvgM2JE4XKxvZ0lktYkkGI5dmZ4PYYxFAMTYxD7cvmd2uqI6MduNy65Jgr0PXE6X7sSC0ehsAKzmlzCenEHyJJDzq2gJhE7DAJBdK9qHVdeHEMtR9bG2PR6dzJiThT', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='Z4CFwZ1SfgFyn0Acpt7OJvJ2g3hG4wRf9D7PDpndoUVcwNZpNccnwcqj5Z4rhkfN0Pz5piRupc1FEAgM9BqBsLOC8tiZnvVzEixiAu2i2ZneFHsyYbUsaRsU0w7A5QhgyYiAq1kPj2yerN5fG18PakOMvy6ut6Ygb9lyytvvIkXxDUy1daVsG4rOJccu0cgDznhDR51QKHTUfieQS2b3GCmOzEU0IafzyCDxF70OKuX24stzF8gCaAEiruLKFBui', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='YZjZ71dSVfnd9whNGTR2iRHl8AaxL71M', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='nUTQKAO74cPeifg33EjjuWgnARHSYxOs', max_length=32),
        ),
    ]
