# Generated by Django 2.0.5 on 2018-07-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20180709_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='7TTbsU6k13lZF3JYlTrHiowqbI71GNqq', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='pcKsfz5DTDydKVEp8DOBCXxmt7HpmNs2tlrFbWm4ajstz0vieMM8jG0OC7YGzTY9KjfFgZSea3DFJ7WVtKFWQmooGai3q1J2MVpL378oWObv4eDbBGZVRloNKNdSzbtAvfcA5sP6GHLxNONUvpIo8vPlVYpnzRXBHoIMFdGQjPYkiXgWJWUCED5ycHtv562CmgTrb565CO8eYxb8l8zWTD4UuNsCrlXd9ayfBLDhAktZEU4Ytnt6DHvW1p35cBn4', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='rzxub1lOB0XGHwLQSx4zNafQER5CcuSlZz3DWqevROLwxEiGCOV8mw2x6zMUTAzSJuq7QoZXyXWopaxj5bQVRX1VwIlspuo0wGbWzFpebVtu3LhFV9688nE4ffotW8f4LKd4VT5kbpk76FKy0zxB60zV9oLrxkrrNTdFsZqJYMLpiS6ulyXdH4czk4W2CI9vkMvwYKwO2rYQ6UZwCL2aGlT343P02kRx5vvHzECQ7ZiODhONLAyL4fnoHO4c180m', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='7oNwKgvgf37fklIULNj8zYgRT58x4mr8', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='pX9jHV702xvxj2LRKEctiZZ0k18xI6WW', max_length=32),
        ),
    ]
