# Generated by Django 2.0.5 on 2018-07-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20180709_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='U2IYxueHngZCH9sqsQaMBk3NE5ZmAVxw', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='Mf5o5wf06ngpQAoOoOpC7ItYxUpxyoALkpAAgVje44xz24R4NNRTwIyIzi7AHsGt6D5IEMS5VP8n23PGI4R8qaRqHXUm1B6VfdVItnbeNkRFf9Rjpyn1shxyQmjnwTefpPRuFa2uas9vB5e5PrZZkJbKXzS12iVA1MLa4KERuzS4VGF7ixHDFWeLJe5mg7vsCNBkcRXTbqxoDE0JfccKyNlaie0BxvIr0UKZBzP3eoogXMgSIsDCVKknwCaEouS6', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='PjTg3wUlLVgnHZXX74D78lLMLdmSsFWHSTM1CudylGYT0kveX3cKVqqKHdBf6Vegzln5xmbJiNFMBAk6fJxYsgERD8xWXHMHk4g8FLM4V3PIbC0sRhbNawc9TQlNUbNeAOBxrr2it9rLpnzOXgt7WNG73IsmM3qnQUMaTeMXQvTlRZ6iQ1YAoMQVodXDkO2bDNRRWO1n3akVDSdaTTULRInu9gVVM2u3SUydVMPoPFE9SqJdatXCBFxEgSIqfdLO', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='E57OshWxhbfYytAb3dvMRGL4hGGw1dtW', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='3YRVftVtTS4GdEoLYgKLz0ADJUJndVCr', max_length=32),
        ),
    ]
