# Generated by Django 2.0.5 on 2018-07-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_auto_20180709_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='IhHmgxBQw34snrWwRTQaAab4xHHGHqMX', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='4APYzw3QvDmmmRICPZkKFSdCVNitGXrBTZrU1pLKX7mXT5HmLF8wdzlq84coixSTOd9AJ9gqQs5vw0SVWriLvlUhgMH7xuGgCiaFcSFTnzMAiMEUuV1tMN1CYTfKybmesAFX774cIeBqTwPyQ97tSLTEJWQt7mccIa9WLVEwuQYBbp4mGNLveSU6byh9fnntJsZNEogIc3F7GdGKL77lGpC83IxQZBhPiMaAiRln0WEvYwVmMVDHsbm7QTKpuPGP', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='LtONRqz4Mo8t9guobwPOq4dW6bumjlHD2oOqcw34g2pr7WdkC5rs3ydkwGw5ilKscuphTjcJZXtexgDdX9YuUYL5SRsZ70Wg7zMnDNwzJIF4cC9mBPdc4zPRHt8cOZpXs6VtmqtLUrMDMuM866HMwWwcSKZlZTN90mnBwP9uLzMBk979H7NV1HUVygqtJksQrzcspleP2FoCeW2jKfB0bWy9ifU8VvR8pw1cPKxePKgjyblJY8oAxqtGsqGqkXh8', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='blhCLAX6unlYzESQDCFiKgAJjxVVb9qw', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='WEQNcD5igfmb6lfeODuz5vSLtokdHt3u', max_length=32),
        ),
    ]
