# Generated by Django 2.0.5 on 2018-07-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_auto_20180711_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='wFB07aVuqULPrYBMblBS6ZQaxZxsbBFC', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='pciE8NzPwiIG6KVgTBA8dZWMvtStyXp6TWW6JSlxIa61qyUMAHYEuc1IR20MBN1fN92SgpeSdOUUwyo7bPBnTe62i1Szty6EkKywjYLUEC2PKKlnySfWeoDBJLnucjMOG5lF2nXCWkw6E3I5NFfkHWmUiycwtsxANSwD9IYmw5bFaUX5zqcbRxpHp9ScERY6MI4AR8wt8bvSGpzuaJi2LJN6DcKL0YrCmOWFAvkIeDlMC0zr594PawwyEdsmHwHO', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='NbVm0pf9WENbgU2ZJthGswUi0cFeN7G6wNUfAQVq4HaKSSvT0R68FWgB4ujbwrnoFCV9npCHjXeDEQF7MthGiyRJyv8FweZWgLRKSSjRQ06MRhH15y4K3YcNkC7j5qkRHRhfTnxKnn22gQG1M8t6AdRz5fZdktqywkv87r317Ig6llg8A7OQ8fdiRPBX1j8qryWF8yPSaKXelAyXkrwxREt1iQnsJGKJa6PJFYPNV4rgW4sI7TRFAicDSapjGupw', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='GPfWg6sDkswGWn3lURgkDN99I2JH2AMQ', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='o2Pyv7FsBeqBNbB2J8KPQQjQGLjWodQO', max_length=32),
        ),
    ]
