# Generated by Django 2.0.5 on 2018-07-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_auto_20180711_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='d298vgcEvkCw3oYxW49n0anwb5zBsnUB', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='u7yEhfxTqlvvGGCtu5IsMlQgeQHn4fdEJEEqeruzmSZbyeJc0W7PBoxA9mO2lfdwQl2nKUwojYxbwXPC3sMjzA6dIVRqTXJVHvrHiDaDtNpW1qKnJUj3ZNy9qxswWjRr2HU2AP275dav895FJMx5TzkTSGjHVoswe2Rt1QJpCnVf0z9exWLxWWszCQKiuA0s1SmfQy7kNFVN5qmF0NFoV7Owu2I9XunCZAxoJ4KvsnCZRdwkcQMfKRxqU15qFAbP', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='6D7in381ClxO3UwRvh5xRGyC5I1e8vHik2ZpHxcfNYW9XC5ablgcJV1h3De71wqfcj98XzmeNbMJ2EkyIp8g69dnrZ5nq3gqZlViL1ww9oEvisa1xFDJZWCVEpQvCLnVteYk9UkBIYVF99PKWBhvmZnAuNr8YLtPZ0JRAypF4HS0h94Ck0H2mKkB6pXSgHX3lyK0peLQ8LwBrcFjSoRxsnU0ojCr9M5fnqFAT974bWQ0pJbDydmmfVDO93HoIfGs', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='rkf0nQ7jbnS6SgEwkxcc9vHbblMcr5Yl', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='b8Mo1bjUzT1WKck6SfRFLxYIQ0Uwbo0n', max_length=32),
        ),
    ]
