# Generated by Django 2.0.5 on 2018-07-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0010_auto_20180711_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='zdTxH7l7D2U6iG7B02DP6uyieI6g2u3k', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='9kkZPRRlp05P7vhFekXX5eCK7UPYumEWxzvqTVovte0N2vehbi09Hg8DFG8tZCyZH8Mdbva532vP28LJ36PHZoTfQvamC1uni00bNeF44hrCMg6hLZimlf3YZdR4o5a9H5vaJx9D4lJcf85U3ZptgNuqXOGfhdKYx5juFpwRqC5N1NKwTAggTAO2V22Ar4obCs1Cy0WFTZ8dZwom3eseBq9eqZTUWKCCqM0o0wBVsXIWXprbpBWn58DQPhCK9Dbi', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='0uAu1JSWdn5GwvLRVvL8XSh4DHiTG0g0rbHPGLEZXOUOepr1mNg6EXJ3qhbhmrmHa63ZEr9v8gaf5if3ddJ7czhfHdzCgHqZuO9HUkAr6RHP1ALyc7K4iOnyO5TCo4rQ4bRNcLbAquNLzembpjQXvmazSnvUKI4NayApcHoW0wyKvLVy5Ge0U4K7YedStFAAuVvpLidTRG78LlfVm1lt7sOf912cQaCLaRQWP7QAJjo7iaMLbrJ1gjHlhLjp8BO2', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='TDLxGmjhHbJAx9f5aOkY1psxud9Uoknx', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='Vt3kuok6HEWtAVtiMiYTxplHRp1WLOGG', max_length=32),
        ),
    ]
