# Generated by Django 2.0.5 on 2018-07-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0012_auto_20180712_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='8VdXiNNeue4jyFEPTyipl1KbiOBuqxeo', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='YrDxwpM7XmW1LHb9nnFoJpIZmmkMYdm6YyScx8rciRnAzP5I6sI5CXCWqhYTMD7G064gIFLxMW9F1fGk5P2E7PxoL5inMtktKJ19efL7rIR3eGWbxtueCVrtd4RTXTptTRsNUqToh1QDUZSPODsY25xgYIeUoJ8Lk7m0l2JRfq92C58goAtc7nfkDQTgitOpf2hzyYjlp0bPIR63DJzVbEMYbx5fAYSg2DaHATHraq6m8f0UKK1ya18gvGHFHDYS', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='s311AQAnktgjErdeFQoKcQ0Fedk9yBQ12HU4It0qoeEeeJgwB2VE46SEtskO8uHShCyltlcV5boDytkEQJ1VKyOwkh1jJ1HxxrzvHrKJxfHfugFlJ9X4X1uptExyKXNWpfFfJcz4iAMQn6f5w4XRgWTkWtx4azL5hGjK2GulSujZdk34yx7Q9sAo9u5THctnlpvpenFWgYSK9dTbiUz5lTGiJTN6rOMm10RmeMX9NZsLV44O8PzNvtAiwb7QNphR', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='2IHYfx7VRGypIre92F5x3qW7PgvdzSfs', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='CDWe27pD78V3nZlJAfkNwz0RQhtw1uWB', max_length=32),
        ),
    ]
