# Generated by Django 2.0.5 on 2018-07-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0013_auto_20180712_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='Ujf9m90z0n5JYt8GtMqxOgaBl8cSOUTV', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='hEYhYjNUcyFcQlYVO4WAqHIGzDBsExivLYRsrZavuq4EbrMJOFPSLoXoHbc2N4V7sFOJTuuK5wZovL1am2HK05MlA5TE3w8INBhujY21948z2OmZwsBjcdefsxGipfboUkD21iFeuMAXYaugHnhwDUiDRYJe2U7bm2QICefQt7fpYv8VCr2BeoGAI0smBGQ8tYrM4NsmaQXFfWWyxtfMvvUGSUXvCByxzWvy2o66STmpvxiZTTBZMskERSVSFf9l', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='t8IJJyRcTppsF4fFp9OhosJTNgIGMuWt4oVDqHZ0dXbl0iZPHDvB20npg6XsnXQxMON5hSyiYvagpN0isYAhz6KeaCa0cYn4kYdKKGGB3WW5DTs7rzdUvs5tnvKHJm2ReVEtq0Y0plal4Vt90ft3wponwYAGUKiKfSSMElhV4WaooGcvRa9UoOJtKCWfZfKiD4UsnlBAI38tE8iGeO8OseMBRtoMOHHph4yXN3K6CTROAKeXwoPoM3SODaEQY58p', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='e1ehOlXgi8dufzSaXPlzfgECjYe50qFA', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='fjd7vhpGZ0MIpWXngy6pTGHXPOZMQf48', max_length=32),
        ),
    ]
