# Generated by Django 2.0.5 on 2018-07-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0014_auto_20180712_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='iW2cb0Vkp3wu0J2nOGTvmCpt5pmPNKKF', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='iEeXBq5reGJyVnjCj35ttMsW5JG0wIGZDlh1jBFmMkcVtVclbDvaqX4miJacLCVlckXUYYUuipK3TwTMfHD671sUEGpZ3wXD4ynXHzwoc28e1zYlnVYfexXWrr1oyCioQD80V6sYji16f5Hn1cg2KBW2099Gx3m01FwHg1RQ9HspeQn8tpyTHeQjZPo29gDVuUIJ3VRJT0pto1QNpHcPUSFzSXrr3RmVD99BSA8NlF7yq1zpBuDPK7tPOWgUqdWR', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='6BYmDiQVcdW2zIS2xUFrXqU6pvnEIbbTUYxUSPKzAgPLY69RWbq8oP8XK8rNCJXmq2Vlkv7WQcpeGXgxpFinNYYEhbEzhX5s5bfDYKxR42PAVMziJVIVOzh76jPcQhBxpEMmUdAZL08IUBgZy1LOg6gfevz6CYcWEyt97w9LRdaAtvplJyRBmB18lOj3zmOd4eAK382JRJLDlYa0to5dSYoa3wYVISk9bA6z6NkGQuArDVuU0Icg4hScsqpulq5M', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='P3xRC3sfrDGpFMV4dYnoMGTO50vec8pc', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='1c6QrJGzlA9s8gXBbjrMwa6W8SKdDRGv', max_length=32),
        ),
    ]
