# Generated by Django 2.0.5 on 2018-07-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0017_auto_20180713_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='1lmjBI3fPxGx3yBfJ9cUOPiwsLTAYqip', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='lg2flajHt9SCTFrKdBYqhLh8zJCS3KvdSoQo1UlK2nznrgEY4G6biHefcCik4OVjwMpi5G2nghvDVjMeygylnbrXURczmndnjNY6tXaTPsTc7kx0fyD5lta69ooiHoRekFn1mrqyqO5UokSdCHqe8SDZticMNSyazadQfGUZgBY21LMnlA2FU3yoTxpd2W3siNgBjfKxEhvBhVi6PtEHROX1SncBJGBJfjEUGHFUgA0UF3eCuwd0YAG4CukR8Wle', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='EsbKOeErOVMuN9yxCheE1L5Ht8BEtABPY8CNAMEP72VGEiKqBweUJW2LLKYZrlGsrV11ABXILj9hjN7GEfQyDMI3U1lk2dTjxt8d96DBPczUOChrqSNh2LDGrhrVrix7TyWNn3C7cR7VNzB2JiEQBQXreZhUMws1VhVoat0IZexZROXLi2VxHIUuJlsIeOVJjApePUIcXGWs3fPTxbZBxOWCkOYmfzP74gXNVgdB57S54VAhalNRgrGxTAkW9s9J', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='2pr7aB2r4JtZ8wwT0wQROAtmi8M1D2HC', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='nw8bCVIToSslLe5Girg0POLBRHXF8BtB', max_length=32),
        ),
    ]
