# Generated by Django 2.0.5 on 2018-07-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0019_auto_20180714_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='l7kfNhiT9BtAUlp955qqctBTAEFsuFMd', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='ZVUJm3iP6MVxVrGkhSyjMDj2u3X2Fu87wcaijSLD7Sem5qQipVyyRKgbZcHiVtKSReFklDX8jKSIqaptOqP4eHgjXZQLEqHNYlYDNdN0ZmpikzMYD1jwduv72EFiPDwRicB4bOVoOUcA47QrIQGHuUW76oBAdy8XjziJt6EqaR4IrFoti8aIxPI0jZ2Sszr5eTc0pBZxGGDHLYCW9yTj0OGTdn8Sjd6TaUmby4cBuuLX7VUwggWVR1y1X16kHQpM', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='rtXPY389SJUxiHufLtEghEZfxbo8uX0NJX9OqE96wqMroUjkMN8XpoXjuDUwJ1ESqOrQ5kTE6idVTvtFVLcd88wLvUKWYHUvaW3aZyL4pxNeRgPlxP5efR5yoBXv19w9haWUcxEMUviYwtXRubrvjvkJMuw1SNRCej4ghYQ2sB5PchmuneuHYRk59kOQBbSNQPlqV1iZXxEB5xSiNu7u3kBsSyB0bVtfeHKA71owMNrIuK27HgNroP8xV7t833Xc', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='s9dzuWIgzXyaYgS6d2UMeQKvynJ61CjP', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='EMDXGWN6nKEGlU9kGVpzNmJGTMdGiiMd', max_length=32),
        ),
    ]
