# Generated by Django 2.0.5 on 2018-07-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0020_auto_20180714_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdacphase1',
            name='userKeys',
            field=models.TextField(max_length=7),
        ),
        migrations.AlterField(
            model_name='nfcdacphase2',
            name='TDAT2',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='nfcdacphase2',
            name='keyHash',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='nfcdacphase2',
            name='userKeys',
            field=models.TextField(max_length=7),
        ),
        migrations.AlterField(
            model_name='nfcdacphase3',
            name='TDAT3',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='nfcdacphase3',
            name='aesEncryptedNfcPw',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='nfcdacphase3',
            name='aesSalt',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='nfcdacphase3',
            name='userKeys',
            field=models.TextField(max_length=7),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='SD87ccHD5sBdWALyhlPR26AqKfZdqv9d', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='SHW8nkEdQ5uLxjnqDSlYBum53NSfUkiR', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='aqfPpdsJrS7WaQCM', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accessingUUID',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='AY5lUZVdIg6l5DWn', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='yLGaDCh1NMOeIImE', max_length=16),
        ),
    ]
