# Generated by Django 2.0.5 on 2018-07-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0022_auto_20180714_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfcdoor',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfckey',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nfcdacphase1',
            name='userKeys',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='nfcdacphase2',
            name='TDAT2',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='nfcdacphase2',
            name='keyHash',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='nfcdacphase2',
            name='userKeys',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='nfcdacphase3',
            name='TDAT3',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='nfcdacphase3',
            name='aesEncryptedNfcPw',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='nfcdacphase3',
            name='aesSalt',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='nfcdacphase3',
            name='userKeys',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.CharField(default='zgrPm0FLkVt3LyXW', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfcdoor',
            name='nameOfDoor',
            field=models.CharField(default='door with no Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='nfcdoorgroup',
            name='nameOfDoorGroup',
            field=models.CharField(default='group with no name', max_length=255),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.CharField(default='XINmLEIVbm9zCoMCJSUeub3kVsq7qmgR', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.CharField(default='wO7zXaiRTLvzCJ3V1R9shlahqnrQLvFU', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyName',
            field=models.CharField(default='key with no name', max_length=255),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUTID',
            field=models.CharField(default='QyogWeGHni06SxHpzIRXyWUCGqjD53wg', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.CharField(default='w9AkWlD', max_length=7),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.CharField(default='d6R8mvlRqUaKFLhx', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.CharField(default='rSUQVKUEVmMgWO82', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.CharField(default='EN29tgBii3cA0vLC', max_length=16),
        ),
    ]
