# Generated by Django 2.0.5 on 2018-07-14 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0023_auto_20180714_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfckey',
            name='id',
        ),
        migrations.AddField(
            model_name='nfckey',
            name='internalUUID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.CharField(default='QTIIVSgZQKuSqzad', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.CharField(default='Cvw4sgCFVPdQJ7VGrqWp5DbtJDrwuI4T', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.CharField(default='tkcZ3u9GnsoINwlDntgRifA9eWrMO4D6', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUTID',
            field=models.CharField(default='P4sSwmpMffN3zRypxFl31fv8D95VJ1Nr', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.CharField(default='Nbp4cfw', max_length=7),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.CharField(default='1iXrT0ZxdjpX8ELl', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.CharField(default='t2PcvhBLTsnVXga5', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.CharField(default='Jwvl3cRWPNBBm1h9', max_length=16),
        ),
    ]
