# Generated by Django 2.0.5 on 2018-07-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorAccess', '0003_auto_20180715_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdacphase2',
            name='keyHash',
            field=models.CharField(max_length=66),
        ),
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.CharField(default='w61XXOLjBqZsiKJO', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.CharField(default='AJQCnpFue4tV4GMI', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.CharField(default='riWpVZvk8LFKtlIAKU5BZzNPmY1XbCSP', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUTID',
            field=models.CharField(default='pMxZBrKCWjXmnr4pkdccbSSKd82u3h14', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.CharField(default='bb9NvFY', max_length=7),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.CharField(default='5nzMb7iT6a2jX57X', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.CharField(default='Wn6fp1BdLHkAvzo1', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accessingUUID',
            field=models.CharField(default='WoIr9fE', max_length=7),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.CharField(default='Sgf3r3pnTMo6A5GE', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.CharField(default='2JgGh6CgqKhrxZxr', max_length=16),
        ),
    ]
