# Generated by Django 2.0.5 on 2018-09-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorAccess', '0004_auto_20180715_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.CharField(default='lt1neBy9A5tRNwJT', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.CharField(default='Td9vX9QnnwqVeTGp', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.CharField(default='olDqv0fTyCzxJq1FX5w4mH7jYgvhXHgO', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUTID',
            field=models.CharField(default='RQEjd925UmeZC6fjCqvplvFQGQhKwX1V', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.CharField(default='IA1ycKjTughb2xcECuhL', max_length=20),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.CharField(default='hOhntrJm6d95SgRt', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.CharField(default='Fm5OQDzh2iM8DlRh', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accessingUUID',
            field=models.CharField(default='FO4m1F1', max_length=7),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.CharField(default='8KsHkkWDvCkDGc8s', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.CharField(default='ec9eUdlM3q9uLkiX', max_length=16),
        ),
    ]
