# Generated by Django 2.0.5 on 2018-07-06 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('nfc_tag_list', models.TextField()),
                ('nfc_tag_list_group', models.TextField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoorNfcTagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_name', models.CharField(max_length=15)),
                ('nfc_tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NfcDACPhase1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userKeys', models.TextField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NfcDACPhase2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userKeys', models.TextField(max_length=32)),
                ('keyHash', models.TextField(max_length=256)),
                ('TDAT2', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='NfcDACPhase3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userKeys', models.TextField(max_length=32)),
                ('aesEncryptedNfcPw', models.BinaryField(max_length=256)),
                ('aesSalt', models.BinaryField(max_length=96)),
                ('TDAT3', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='NfcDoor',
            fields=[
                ('nameOfDoor', models.CharField(max_length=255)),
                ('doorUUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NfcDoorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfDoorGroup', models.CharField(max_length=255)),
                ('listOfDoors', models.ManyToManyField(related_name='listOfDoors_NfcDoorGroup', to='profiles_api.NfcDoor')),
            ],
        ),
        migrations.CreateModel(
            name='NfcKey',
            fields=[
                ('keyName', models.CharField(max_length=255)),
                ('keyUUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('AESEncryptKey', models.TextField(default='IT0744DluURJR4NoDi3QJXhA1DG79RpX', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NfcListOfUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('TDAT', models.TextField(default='hExJxa5fsIurFoXQAQlVOk4lptlm7II3nm5PsqtW6yswQi8GfoQ2bJsvAlKv9ry8OqEWxdt0btS02hZqK1F3Gf0BjBTVpnuMJhOXmCHxNiHyFE8LSVOJas3qJROVyzWsF7xYjOjbzzkegYFjejdtOrO0plFTSklCynhO8esXk4BdwGZ9g5hABnBKtzYm8FKAorr86ptb7Y25SeOWacAixu598CbQwHZI0jgxwXTF9hit9nX1ArmGK7OsJE0okPqy', max_length=256)),
                ('accessingUUID', models.UUIDField(default=uuid.uuid4)),
                ('accesingUDID', models.UUIDField(default=uuid.uuid4)),
                ('encryptionKey', models.TextField(default='uaTAIsZD3Ez0nAIkKAc9vLZKm1avzrlX', max_length=32)),
                ('encryptionSalt', models.TextField(default='RLfxwhMgFXy2pW26DiEoiErSMvqp9bim', max_length=32)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('listOfDoorGroups', models.ManyToManyField(related_name='DoorGroup_NfcListOfUsers', to='profiles_api.NfcDoorGroup')),
                ('listOfDoors', models.ManyToManyField(related_name='ListOfDoors_NfcListOfUsers', to='profiles_api.NfcDoor')),
                ('userKeys', models.ManyToManyField(related_name='ListOfKeys_NfcListOfUsers', to='profiles_api.NfcKey')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
