# Generated by Django 2.0.5 on 2018-07-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfclistofusers',
            name='listOfDoorGroups',
        ),
        migrations.RemoveField(
            model_name='nfclistofusers',
            name='listOfDoors',
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b",\t:\t%'d\xcc\x12\xac\x01\xb0W\xf1/\x04st51Uv\x82\xa6\xd6\xe0\x16\xf4z\xc6%7_\xce\xc6\xe2cZu9l_t\x8a|\x10\x8cN\xbeo\x1c\xe5\xa0H\x13&\x1a\xcb\xf2;\xb7\xa0]\xb0\xc3`p\x12\x8b>\xc1\xa7\xdfu\x16\xb0>Yz\xb3\x91\xbf\xfb\xf4\x17\x03\xac\xb1\xe9\xa9\x99\xdf]\xa0\xf6\x80\xcf\x03\xc8\xfb\x9a\xc5\xba\xe7\xac\xccZ18\xe3f-\xc5\xd0\x1e(\x8b\xb0\x8fE\xbb\x8f\x10\xb6C\xddT%", max_length=128),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='CNo4XRqN7kRKl8smPAD1o5e9keTy8VeAsuRfHBU45NEqnQdbvjSAVxwA8lgGbRHggbpEW3vg0yixQGgFyc31Fgcp1IbnZKuHz4aFqH1VUR3BDwiM86k49oix2sPIH7PuDbMTSUCeVjRmepfcJ1u2RAJoTTIb93ZWZUYHr5QUzOhWLcYeBC97vJmEqdhdbTglPAgZJwEPNcxJD1BMg1ftSIOTHqUsuNqeotueq78PJVfSNBX2whNeFZTt1t5J4g7U', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='OzS4Bbf5QTUprfNXeEVHhR459Lw7sqGRISIrg863N7jJedC8UhqH8nHrUmmSCxoiF8zWnklgCUWtKCKQ7y96BJr39FsyoEAj0a0KS6KGLDPniqqCNgICCgXbRsQa5oL15CfeHcAcMVwNpYy0WXc59rQw7Y8LLOCqmh5mJcM1KxOTRzNrleaiG7YglId9KWdEQkgVGur0nN5nAY5Qubyfoo01kTo8X90km783bH7vseXXGbNQxnRpcuiCyBFsB6og', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='skoUAppn9HCTWHPsfHMMsSVNLcdmboH23aBpXrZLeGmX3YJPrySTQbTZ5tPqA9gsbJ8VRiqrT6PBnpLzb0QjIstU9m2y9uPMCSqjLoHTeMVBXl602DZim22VFGnXaiKH1b8V3r2UPTfoVIOQN8ZKY5qjQLygxsOane0YCfX6eWwEUAgFbDaQEnqEbLbtey1MqP9RDKKZjeFMH1JTXHxCAnC2zH0TB9xz9Iwh6yzXezF7jKqnTBmR3V0KWa6P7vcW', editable=False, max_length=256),
        ),
    ]
