# Generated by Django 2.0.5 on 2018-07-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdacphase3',
            name='aesEncryptedNfcPw',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='nfcdacphase3',
            name='aesSalt',
            field=models.TextField(max_length=96),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='1XcfmfROcZkpaPZLSOItYJlvn1Vq0wOM', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='PqcjKiGQ7L1HrhkZz6YbLAk1xVvp9kvLdjRh0WyXUIN3iw0Z4O2I4NyHw3gBt0K0yo7pgYhS2b66X4sDY8So8CwbbUGdz3MhE2yxxyeFHPdCcNhbs8o7L8ns0z2xUHdBZ2ExSssJmMlXN4qyAkoIsSPsYbg9FCeLQz8lJL3KBA3LNtV1lhDBx2fmE4oFgPaTM2zdkQM5phhG655oh96Z8zo7YVFAHOMyVUnpqHnpyeRW0Sod8CZjclkwF5ff0tsi', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='RZPiLYlgo6dD1pBL8ONYH9UNrx4EIjHXbRIWvcyuAknkvflGGJnpk4HMJJuCa6JkXCKqTkCAbSmYsOvNhOdAwI0OsPNMDAt6rMKwHyAO1iQaUaImHMA3dpbaMOwmPJ8qZFciFSNJoHwwWo7sAXd0uprrVwzo84WFf7CuDbN6ceHK1VVSYFcEJnmixQ6jFEcQArvmPvE7L7lcZxxoQjhPMuNLGxOhHg3FBZ1IsW08vY5HKZzS9VBmiAxKZopo8B1c', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='htsUsQvDmC1LvYJnn0pplA1XcNWLa8C4', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='KfiPW2jmX04VbGGIRkSliVk6z1614flN', max_length=32),
        ),
    ]
