# Generated by Django 2.0.5 on 2018-05-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorAccesControll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nfc_tag',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
