# Generated by Django 2.0.5 on 2018-07-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20180706_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='QUdyED5ypiQVoG99cP3TU6K0r8ilA7nw', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='JbHLhf3a6YdcIrBFBim7Yc9GrQNkPTTIoBhk3604tlcokxy6QGdB8005pysWvEHuKdMY3VL6nRtmtm8fB9IlrydyKSkHSm40PeuTkFMpiGUfy22YiN8vSrdLcla4Fmix7Srcfl9TwSNowS6xdB5GKujvLQWi9YyON6v3EW1J2seWblzEp9YQUs7NuUBxUpm4Y7pCZYUwfkAkiiOEN1868Cg7hHLx7tcV0SeSM6dBsSY7S9EilhQUt2etMMow5ZGz', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='8s5tPeywOvyoNha8w25xIIStgxhv2cTp1CmViix5hAFQrJcQroeuAjkQy1MrgIUACE4ugrisXjZ56nXaauuSh2U1XrEBddQo0mcCyu9RVTcXf1fB0BobfDghEraMv63qo9pqzCqMwZFmTAYY3JkrUEn8OOAgQmjU1pl8LcKjMt4PLwH9YzilXlV2Ozj9eHxZRCy78e35l3WXcpCHO10FUomA1E29ESGcwP4dijXj796B4PEqjWuTa7XHFw7RRicV', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='6dMTzgV3pHMkDrdoxLkZsi6QsRmcgF9G', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='mgSoMRrCwrtuBqwjOFy7Dh41LIc6WzOx', max_length=32),
        ),
    ]
