# Generated by Django 2.0.5 on 2018-07-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_auto_20180715_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.CharField(default='BgMr1TfNu3kDGZ8e', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.CharField(default='eHrXRuwn6TO0A3vE', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.CharField(default='857AmgdXThVy8rr0FTqLKXoQNE87X9KF', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUTID',
            field=models.CharField(default='iJVWPNbn0WeJvjUSQSMmeYhDwomEKQYh', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.CharField(default='bchVAap', max_length=7),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.CharField(default='GPKFmfAZqHfaJQ5c', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.CharField(default='ia4CSZjfkrH67HzR', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accessingUUID',
            field=models.CharField(default='r1pQ26z', max_length=7),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.CharField(default='cmp9AbiYlnuBtKMt', max_length=16),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.CharField(default='aQcZzcIaTmYEjkWt', max_length=16),
        ),
    ]
