# Generated by Django 2.0.5 on 2018-05-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20180503_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nfc_tag',
            new_name='nfc_tag_list',
        ),
    ]
