# Generated by Django 2.0.5 on 2018-07-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20180707_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='VBVtwwqtMcxdQMvnEJN8dMVz7Vx2wp7K', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='toGCC9uIaRfMTjRl4ViJOFgF0IdMsY2zcw1PrWG0EnUcRhCJzzaK10ye5Zk050boz0OwZjXC7IKYnBZg4WFYKNQoFY34YiRE2GGKj2djNmJxJthqCapDD2jlIZNg0ea5kP425qr56Mr6AkFnONZgzEtNCFyVwOIMmr6PRheVTQOlWqRpUytsitJkQdo9dvCGApRG8rjFK7RM3yKmukrL0bEZEJ4sGjfDs9K1Ta1WuEaJz9XcCoSqQ9aovklBcw61', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='YMylK17FoHebisIlp1jli7WLDoqDp16Ago6e9WgH75VWeHsm1Fqv2lUw5GgzuFbycMtSdlnkEjHgPu2nClRUptSE1Zfy02DppCEEzNk3BGUU0IbFkbePRv1l7aOXhGegbQortTz24u8ZVPrcm0KBsYJH5EAP64juDqbUi0POINGYcQmx8jV451Rc7jLvxVQQjK5Xl7xkrbqsme28vxfdMjpNZCiBrDpPujPgiugCpf9uBYceTs5dg6mRTbiRyjtY', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='a04QU5yQ3UPNcUNX7wC3yWO2KgCBjq88', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='KkWNV9yqgmf3M7Qgd9gvMo3aixgkfkWJ', max_length=32),
        ),
    ]
