# Generated by Django 2.0.5 on 2018-07-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20180704_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b"\x9b\xaa\x82_z@\xa1=Q\xed\xc5\x85\xc5\xef\x9dy\x00\x1d\xe1\x98\xf4\x1e\xcf\x85}Y\xbc\xc9(\xc2A\xa1\xb2\xe0\xd0\xfe\x13\xbb)\xdb\xa7\x8a\xed` \x9b\xc3:\xdcj\xdbP\xe5<I\x16\x11\xc1')\x9a\xe4\xbay\xac\x06}J\xfam\x0c\x06\xff\x94\xc8\xf3\x89\x18a\xde\x12fZ\xff\x15u\xc6\xf0MZz\x86\x9e\x06~\xe9<\xb0\x83xzN\xe9\x08]\x93\x80\xa6\xedG\x1dE\x11\x98\xf3\xd6:\xd0\x13'l?3\x9b\x9cI\x02\x87", max_length=128),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='GRuWJFNX2VCnrzdsL3CiXpOq7Bil2iovluauNfn6rgDBQprnTXa19B5pdY4hB6PBJMeDmlyd5Qy6Ui5gJcqVp9WVW3fPFPvxF10Qdg4RhGLQD4Xv5N3vvPdTgOfaBOKDQ4XVRyx1xaVl2NRSsBiKZhwtKRc2lcJxVQsKXDyO62BQMeHxDR7LuJE2eiViE6FueUy2Br4lDzjTzQ3cyKqmuW7QaiSRGh8gvc6ShquTOkKJ5GYjLtyGEWfSRKFOSY25', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='5ejtGIoXKi1uGVP8uya5dRLI47diauCxW3MUw11UT8BWCwDhfFzduuwetacu27evU6KlbSElZcssQzMXD6ncW76pVcjIrwh7RUrjhAQrAigkLvLEgTEoLCUzJmQFFij2ULfQFc94jzNVbqtpXYs8xY7G1F86LX9b1y2yoEYbJgdvCSowlbfxMnjLT8rmms7ZeHs44gEPl60tztuckLvdAcn3mPPCpglqL1NJHeFG33ghGzWHGxUeHrlYqvWVJ1xI', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='WmE4hS3vYHLVVyuVNGwXNZrr7t9AkjI45bJrAYJ8Dk8yCGFVLoVXV5Rxk2wsGWXXcPNOe3GN8YTd1EvORxUSBOQRyrnqyDag0GcNtIyfImL5cG52K3PCxggG0lSW6XoVwGCNIH1JobvsVRPvztppaqdyvqbNrhIIe9Ud33QLOk4KHPML7PdUm4isJZlTn2OhGKYt51gNg80qcTultqkSZrbWdzbNjObGH4A6wo0pT4GVtnOb1ZNVbNlUCJh0MG6R', editable=False, max_length=256),
        ),
    ]
