# Generated by Django 2.0.5 on 2018-07-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20180709_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='7gM9MNkLMzVpOhKdKcWS0pi7RHhoLFOZ', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='ODVrN2s1QdRFIZBmf7ngWn82b7IILhdReLAJ838gywsTt6zfKgisupFY0mo76ACom8Ikorzaf7H3YTzRflVOfZpnaFU0xRVFHfJF658ENCkdfpkmEuF560RZgqHQbJWU5Q2SpRqM49M4nIdCbe1jDgF5sW5F0nqXKVgtyEHtqtkerQ0H2WP66yHQ2smSPqIZbjUcEKFSdPkVYSvL1mS22ILmBQT6bcoXp7l3kJFPIvx6Dq5QZJmEIt4is2JkV0TQ', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='3tfLcq28GiZ24oktN3hRqzrWGgVyjUyI9H2dxCiDDzkxxLhtzRk0SqsKykYepAFtzqQIKishxkzfvmEit3hMncsvMllyRqmBJ76bjKusXff9NdZuSh2eBfoP3fN0OPVxjXhOfPV1zMTfjo7qBDk75EiIYubp9bfVgNMYxirIBtfoT8kNZgCqj00mjFRZpaGFhacoUv5bwBtYR9axqLtw3RLk3tFQsOwghhvdmG6Fi6BZ70IkrEBq21vLh10D5lMD', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='N6bJNTNJjjxUtRm8HLi1lrFZMO6J8XZV', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='YnCVKOtEXtc8eccBK60ogQFm4codXlLL', max_length=32),
        ),
    ]
