# Generated by Django 2.0.5 on 2018-07-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20180704_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b"'\x9a\x88\xf5\xc2\x0c\xf1PP\xb5\xe6\xdb\x0e\xa2\xd4\x1b~\x14\xf7\xd4\xa2\xb3\xae5\x96*\x91\xbb;&\x9fZ/\x06\r\xf3,\xcc\xc6R\t\xe4\xca\xd0\xde\x13\xf4f\x95$q\xa0\r\x933\xa1\xcb\xd9;p\xe8\xddK\x1a@L\xac\x16\xa7\x1c\x990\x96\xb1\x98\x1d\x01\xb1\x9e^`\x0f\xc6)tx\xf3\xf5\x04\xc7\x97\x96\x86*\xe71\xd5\x0b\x84r\x8dkZ^x\xc3\xd9\x92\xc2J\xf3\xfar\xeb\xa6-G9\x05\x1d\xd5\xfeBL\x19\xca\xd8c", max_length=128),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='JWkBEgDe1we19FKwUgmcjCAK586akZEkDdX32z3ZElXAzbCv5kGKTNw3ZH7KqWBS6T9YjHWHED6br4mnZLyd6ZlrLUyPQsXPevGQr6cFUiDq9VpWGWrN3L3BseCTNfDw17Hy85HjLFSp4LIuOJvWOqbjif10k3V8HflzYNyEyU2TLUgUMCYUGW02jvu5noKnaH2bqQQ3jWW9mg8ojxN7hV1Ojgm3TaIj5h66hICqa0TNvoElFusBnDkoAp4T06Lb', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='dApdNIWQxm1CTClGag2dydVfmQeTTJ4RtFWWNtIZINAYZ2FIpZqt7xUTKUPaLcgqGFFeTRtHmCLXHraQ4oHvaiB7kN3KNHWqRz6RKfCVEhZlSvt83XzptJrrngrN0PlxZVrILJAG3JoM4BmVvcLKu1mEdhWFRXwRaYV1BhEOtlkFJrDmkBHKjANqpumwu0rugvfELvJlnPS5vgLnpP2oxscohMZjfpqBUbvoI8HpjqiEiIfBcOFyP6ALWEgzkVP1', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='u8hClmueucaZ8MWhkbji61C5oETQeQL7hgK9KAPjEVnUHt0ShhiPXQnoEvwfJ1XD8TRYfIi29W5XUrZoHS2fg8ZsOset0BLRGHcKT6dt5OUBTW5EpivcVI5VVyoKs1VShWpPB2xaBNfypiR2UjKwwtWWVkitS05zy9b9OcJ78gpSouqf1OG0jz8rYfSyvF1WbDQBHL72yXtTqeLOkaAMUlaSupq1yUvuaAzv4bsUsfPYDUueJjMs04qPxuVXYkDe', editable=False, max_length=256),
        ),
    ]
