# Generated by Django 2.0.5 on 2018-07-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20180709_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='louQG9It2Fq22GAMX7ViKqHKBQC4eSBZ', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='RiRbWrkdELfMzeqFmCzlkBWH2yjOwZShA6rOBpUiGIQhmjliS0JcTkkKTTChtZVkcvajOFfIIfVh8MxsLD93XyRE3auRsR686a0xQDGFIHr9SbOvHYWOJcLMDe6SwngsqZpLBOPAU8E2ExSMWwhRbGvA57xDt3zDGAQZYRKuVvU5ddFB8CAGjHm3itcqM4L9LfpzHC9UTiDHrbHc9jsM1jIaUSElCbDPL27Sn6KxEB0i6G1ShcX4O97uaRrHvvLJ', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='a55V7znWUhBVYG83DDDLiMUA4KOM5ukBArcXZc6ZzwpvalqD0nNYcTzeGWjzJZkHDwpNsMOZN1k8jued8gdsGMT7Ho4wrBeNu2FeZ6vcYNwn162Ur3JSEigXu8ekqxGSYpH81DYKZu6tz4KHkv4AukacmbEmVRPBv8PKSKNNPNM3jepEBZI5Lkm1owJaUNfdW4uun4m6JilFndxgJ43QNWKUe3M1ZHmcxPo1gTub5RlZ6FslVt11wTmIf9zOT4bK', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='Ob8s4weJYiwsIe9SLrliDBTRkpVLN1Ve', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='MjteITsBWdqeoVpGPPFrtuvtyIWz2PQ2', max_length=32),
        ),
    ]
