# Generated by Django 2.0.5 on 2018-05-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20180503_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorNfcListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DoorNfcTagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_name', models.CharField(max_length=15)),
                ('door_nfc_tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='dooraccescontroll',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='dooraccescontroll',
            name='nfc_tag',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dooraccescontroll',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doornfclistmodel',
            name='door_nfc_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.DoorNfcTagModel'),
        ),
    ]
