# Generated by Django 2.0.5 on 2018-07-04 20:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20180704_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('3b2260dc-ec73-421c-b77a-0d2e88145d7c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\xe5\xb9B\xa8$\xfce\x98X-\xaf\xe7\x83Uco\xde\xc0\xaf\t\xa7\\\x80\xfdH\x10\xe9\xbc\xf7S\\$\x949\x83\x04@Z$\x01\xced\xfag\xee\x11\xf4!D\xfb>`b\xbeR\xb0\x03\x96\xd6\xcf^\xd1h\xa7~\xea\x18\x0fG\x12c\xf6\xc2\xd46\xab\xf1\x85l"4\x0c\xbe\x81\xa1\xd16\xa7\xf5a\x01}\xe7h\xe01\xe5\xeb\x99\xe2\x9d\xd3\xcb\x9ad}\xc3J;>\x9d\xd9#\xe6K\xafE\xd0W>X:\x99N\xbbJo\x0b', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('498f49f0-5407-459e-bf26-87effb82f1f4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='3jYvXqTjJoKvwwPPzojnokQRs74Y6e8QGR1TSnIphoEwhsTAEq5ZUie52JSSgpM4CYxRUfkqoLhmThTGRVtrnOGTPJVgBoAXhuxHL6fWc9TL4CbNpIUYkKbRut0jUIifxLzY67MliHRSsBRIps61W2oQFYjXCTxepUPKFObnchiufWdidaNDx9OtHOZuBJblaIX2IDT0XhvS90H9HvBrimBmCv9lrdfGVeOtBYhD7hY4t5Ym8jQpqxwcy1AQHX9r', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='HOjgtMnM02G5vxO55cC4DXOZ12N9l26CSutTeMeALw6TmrLiJKdDv7nlyrMfUrhFq7SV1Eq6a365NYY8y80H7CxLziOPDwDTSMkt2j5ozmc4EwJpUsPAeoJSxEbvtVzr7danuNu9wXFuIJMTiKHECcVLOYhgTLVNvLkaZ3TGjC47MUQF4jzoHfxWtCBgGj91sjQ9q7W6i4EgU2r7VE0JHa4MORmWleLCzfr968Eeu5yYCRrlXHXWXRDScc6wASc5', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='pOCM59c6qnyQ1ebJENgUpqGmyBZsZr71lTtGnT3YQ0QOJqAqvDstDRgYD25k0N6B4SD9I75rZnOWUQa6qM7bpIolNRxg6rjCJp26w0ej53mS7nIKACIyBrL3ONOZo1p9tf0n5FmBXCu5ORV9YvEqbo2cKriEHCrSo4aJkGDAhujrwp8BtTKLZEAre4S9iWqSS1ErLC5efb3aQCMOXaxMHDRVKp1U5XEByeg4tjzd11rSvZtOIn7hM79mTfpgmlkT', editable=False, max_length=256),
        ),
    ]
