# Generated by Django 2.0.5 on 2018-07-04 20:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_auto_20180704_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('5956ac65-d044-44b8-ae31-77bea9bb3b3a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\x08\xaa\xb8\xdf\x9cU"\x1do\xb8\x01b\xa2\xa7]\x14\xeb%\xb7\x18\xe9h4Y\xd3\x085B\x1fT|\x0b[\xc2\x07=J\xfe\x96\xce\xb7fn\xc1\x18H\xaf\x9f\x7fuN[l\xc3U\xad\x056L2~\x99\x1f\x1f\x99M\xa6V`\xc6\xf56\xe1\xfc\xccg\x9b\x8c5WkE\xdb0\xc3-\x06\xa1V<\xde\x98\xfa{,\xc8U3\x99\x16W\r5x}\x14S_}\x8b\x98\xee\x06\x85\x8c\rK|4\x8d\xc9\xec\xa9_6\xd6\xe6\x98', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('aaf28c7a-71d9-4e9f-914f-56c0fa1c1f6b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='3GsHGjES8nuibsNTML9b7lAKmEeEkcQrVoR6pmpPn63dZs4Bhb8eoiApadBRBm9itNpkwrfuhqZrtym9PJuWFJskACm6LYHMsFR9mZ6UBxYAMEUha7i1IeGeiGPyUEthxlQA0eg5hSCioC8zTjWwxxgYF6sDnJVY6p6AUB0BcgI2IcXKdfNXLcH0aZktubGloQoxmcLfBX8EoloY0u73WRNjC3DEH92P0DUALmNk9gbpfa6j0AaD93fsIkakKFxS', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='5gqhcN6kL5tkrMbwdwLB3pNRsLJ6lCvkdpgvsXoNWqM3yGJM9keZZd3QpyNySRwUIJB3vFhVpFRVmui9JNfPErPW6RxRoIxoaTthMnxdeO8FaWdkWzLbj4bP7wG2hgTL8kUMSx1WLZC9hdmhhW36xsbsfl4IOL2g4XryuDw4lDdpK8r20Cm8kE9uuVvoGY4ZQ8lju3IsAViRTXBvOSQceNkEVjjkrHL9dJFL6WWGeFrzmC2dqnCsbPDD8szHNkzS', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='AN0I2E0gcBvFb3iWF5lsRSwNppFThQO4hIdleoKBKkhbGUDvQTySMZROII5IprNuLLRBe9zxKx7JLa71PA4jl9RXAmaG80WITBnBoFoFkPZxKhqMzgaylE9F1NewkgCGr4a1Dtm06MFpFkTEd6tkTAtPvMW3AkVQkRGxzW4KgA6LLymFeFl5jMrjWNRX0BoZLFBxQzrgjbUIoz7YXl5rzva7cKdHqh2AyERSx9fgXZeVYy1mmdmgTL3Y1ZwzAF5f', editable=False, max_length=256),
        ),
    ]
