# Generated by Django 2.0.5 on 2018-07-04 11:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_auto_20180704_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfcDoor',
            fields=[
                ('doorUUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NfcDoorGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfDoorGroup', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NfcKey',
            fields=[
                ('keyUUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NfcListOfDoors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfDoorList', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NfcListOfKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfKeyList', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NfcListOfUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('TDAT', models.TextField(max_length=256)),
                ('accesingUDID', models.TextField(max_length=256)),
                ('encryptionKey', models.TextField(max_length=256)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('listOfDoorGroups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcDoorGroups')),
                ('listOfDoors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcListOfDoors')),
                ('listOfKeys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcListOfKeys')),
            ],
        ),
        migrations.CreateModel(
            name='NfcMasterListOfAllDoorGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfMasterDoorGroup', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NfcMasterListOfKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfMasterKeyList', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='nfclistofkeys',
            name='masterListOfKeys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcMasterListOfKeys'),
        ),
        migrations.AddField(
            model_name='nfckey',
            name='listOfKeys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcListOfKeys'),
        ),
        migrations.AddField(
            model_name='nfckey',
            name='masterListOfKeys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcMasterListOfKeys'),
        ),
        migrations.AddField(
            model_name='nfcdoorgroups',
            name='listOfAlldoorGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcMasterListOfAllDoorGroups'),
        ),
        migrations.AddField(
            model_name='nfcdoor',
            name='doorGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcDoorGroups'),
        ),
    ]
