# Generated by Django 2.0.5 on 2018-07-04 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_auto_20180704_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('e32dadf3-f4b3-4511-aae1-4259044cb572'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\xda\xe0\xb7\xa1nP3\xc8c\\\xba\x9e\xee\x89a\xd3+#\xa9[~\xd6\x91\xdfw:\x07\x10\x99\xa7Ijl\xce/[\xd4\x08j5\x9fs6\x8e\xbf\xc0\xc8\xc22\x15d\xd2vN\x1f\xeb\xeb\x02\x180\xa5W\xb2\x16=7i[T\x98\xea\x12?\xbe$\xe2\x04#\x81\x97\xf9\x15[:\x8a\x88U\xb9F`G\xae,\x17\xdc\xcc\x88\xec6\x06\x17x\xf4\x1e\xd7&\xf0C#\x06\xe2Wh\x0f|V\x8db\x84\xd62\xbf\x83S\x8a@\xd2-', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('0f11fc35-7aa7-4eaf-bac0-ced67fca75eb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='apsRYU2ruh7tRe8OOKfmShLoWIVKucIi6Dr9DMfAw7gNpgDAmF8ubjMseBVqvAgazCJeDtV6VKCpuWEdqbyIviZLiPGl0zvQFnybsYWLxdAAgrBnSv06weOFIF0JGcEzYm48v5NAbgc3fZsG53aWiF6JnN3S3ThiksA6dI8nOPvwgZzR0fz34A0PVHGCxc1lkA6wwD1JLD3laTOXdAxsUIPIwLiNHCPtSYn7d0qh8mtMr4xCkimYOtG4N5BiD7B6', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='fMdgY3eHr7MWanrnoo6QzPAbEmxjLywDdVoWzc0iLMdlMdf4EQHQjRiEBa0RF7JTra2TVRTfwzSi7qy0SAVroEmdPM19F38mIUADUcxUpHajHIelC4z7uL0pDi5mgAAQZRIc2bfcDBaCJDfTGPnA0hv1OYU34s8zzTAKPvzzlJuUaWDHWSoaSfu9CykO6QrIg8xLUulc3lnXywP8LexF46l4gPH2HtwY4NUfIrJMBez54LkTiRgY97K0ReyThwNS', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='opLQckcklnOc9wzRQi2MmyYNXjGVeUHTNdb8gqT48c2ngNNRyAxHM5vxABBGvpdlt7sMMVSuWyymh97QhwwQhK7TwM79NsmDyP66sHZYsdV2ZRD2stZvy3ubS6Qhsld8liSuoFfhlbE0RSxayxsfkfTost7BH08UgFjOacXce5TJ2aW5aGHCGKQDbHFIicSPtO2LWYQTaESHG4vzuAyGQMixeSwnCPae9QXKFhqVoKkn5ZD5ozbaWUeZlN7ciuid', editable=False, max_length=256),
        ),
    ]
