# Generated by Django 2.0.5 on 2018-07-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_auto_20180704_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NfcDoorGroups',
            new_name='NfcDoorGroup',
        ),
        migrations.AddField(
            model_name='nfcdoor',
            name='nameOfDoor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
