# Generated by Django 2.0.5 on 2018-07-05 04:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0008_auto_20180704_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('5116273a-32c4-4032-8666-56c80ec28fe9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'B\x17\xa1\xa5\x9a\x85q\x98N \xd4\x1c\xe1\xab\x87k\x03\xf3\xf1\x16z\xa0\xb9\x14\x9a\x08Pw\x989-\x84\xbfu\xa7\xde~_-\x8c\x0e\x1a\xa0\x14E/\x922\x0b\xfd0\x9c@t\xa3\xc2,Y!,\xb5\xa5\xe1\xfa\xa7G 9R\x90\x11q\x06\xa2\x02\xcc\xca\xfd|\xed\x1f\xf5\x964\xc2\x04[5\x10\xea\x95f\xc0F\xe3\x1f\x0b\xe5\xb07\xc4\x07\xf1\xcd\x92\x80\\\xf8\x9bH\x8a\xe2\xa3y3\x86\xd7\xac\x98\x0e\xb0\xa8\xf3\xec\xfc;\xcf\x1d', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('56f4741b-516c-48f5-92b3-a0a0aa7b467b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='dWKaPysIBCQFkGgveTWy83m907PdR7i4hwT7QGDVoOkGS1O2qMVWZ2xZekFGJBuCNoRafUZZsS6wH7hszcJf7IGM76xlwLkvAUW56oe4W061Lc1lJp5Uh1ZrkiEk5agKBVBK29ehk0O37sDe1Bct7MNC4S1wESHqyneQC3AjCBTRQuUb7261apgPEBcs8fBn09MArZGAuvQQorCTY5deDXwGHJ80hdJvoJAMayAGdGEXv0055b6TW3VSWveNLPLH', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='ndcN7RV8ToE5L91WOjbwNEfIW0E69rZ2H0yBU0z6ZxYelBOuGIKJySuYxBvbO9NzPTZLxsbJlVOIHcUc53oBI4jZcqoOE4X5w2f6Oe0sXyGRuiFqgxB4zmzl4Le1yhTtumrlHfFqDfqXPPb73XDbKIoz9XLdC5rKMZ8Op4bUIwZ17ARjf4wth4jiMaA4UDzUdvduYd8GsWzYBBQiSwCNT3YAk2VbTpEooIenTNVuxeb9z6FdA39CBizpvV28qth1', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='8R756tRM8QMs9eXRS87A0TW9QoupDdKSPGRu2kYYfLv2RUNb8XlzDBN2BUzT1gZfibVsnEXcvroGJxaidACOfMGBrK5bXwRdgBlvWtcEDeZdEwDwWG6s7hULbXkAyxsqXGxDJPLkDyOeAFDqIXb4yPILyS6owHnjGhhdivFo5g0KZiNPs1DAeBoe147gaLDA31aWbGfbnNSOTxhQbjdW0uuRFxjDExJuuE4m23CfdCND65TH71b0vZhiNwWgR0QK', editable=False, max_length=256),
        ),
    ]
