# Generated by Django 2.0.5 on 2018-07-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0009_auto_20180711_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='4VsXscy029v0266gK7tGC1OHrcyKkx4G', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='sbcPAMkQwRYzfXNn4rkrGe18AbGBHPuvnsUsXjcdzKks1IC75GY1OVAZ022uDoSSQYvkaE8CKyez7lmrQENaHO5q7CVXjS8fOcXkFYT2N89XP04sCQWjv6FluRVB9A0MXKXeokNvvfYqKLxymwHRuHPuUonBlJKHxKLY23lL0te4t1y2YZ8bOuE5VPxS7DxVW6neaVq5ZqI9exnumvh28lDK2FFhs4T9LtX7GhuYhGsTAktkvnIcdT79k57Vjj4k', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='OVd1NK5wQm9xNK0oxPE60E1QgK6sGPIpX4j5QfmNVYoiqEqwcFndoNkd6bAE31Jv2rO7ZpgJ9vaF0TOC77paWh5AM31S58ZYHsKDrcxwdMSrTY7mzQgZuIeSzI9JKAE8S6t6fLb49u0JiSEsOjUdWkNxrkPMSfSTtoSAromtB9hoPXovJicCu8xcGpFd2ZNSEoszrJi48aip11dumZTOGsyu6WDh5TkCkmKwDskkYLKk5wwa9yrtVa4Ec2SxrmnJ', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='i87ctXgBVIqQIWmjg3C4YlyFDDCj0DdA', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='LzwMXdjYeCmaq615y6ClyNZ2vomktTNp', max_length=32),
        ),
    ]
