# Generated by Django 2.0.5 on 2018-07-05 04:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0009_auto_20180705_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('2206ab58-d0da-4d9b-8226-135f640aa4bd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\x11\xa5>j"R\xb3\xc4\xf4\xc5\x0f,e\xf5~<1*\x0f2\x9cn$\x15\xf26\xd1m2\xa3+w\xdd&p\xef\xd4\x90\xa4\xddW\xb3Y\x9eX\x9b\xc2q\x03\x90b\xbe\xab\x8f\x1e\xb1\x95y\x95\xd7\xd9e\xb6y\x03a\xaa\xa0\xb1%\xc7G\xb1\xb3\x84\x1a\xfb\xa4\xb8\xd32?Xn\xdd\xc1\xb0L\x93\xcaz\x18\xdakC\x0c\xc9E\x0b\xebi\xcd\xb8\xcfu6\xd7C\xf0\x99\x99=\x1aNKEg\xc4\x92\x9e[\xf1\xaew\x10f\x87h', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('420694be-2f0f-4349-91f8-0c8078fac3cb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='uVnCUbHBVloDO7gY7hcyGIMuqrccGI20tu49TfWXb5ftAf3luIwS5lFGH0E6DZhxidnq5uUHePz31tUmSkpEBOihZ1GPUMtwuKzUp3cWZqxaErhucOWaRIiCcHylnqwpXadJQs3noLIIG4t8ggMuq2VI3Bra5Azvirj7Yh4qmCWLmYt9QKEsz5WC3P0FrGJFnkEVyQNKefb6g4Idk9PRz3K9H8U1JIhtveqpUHnQvs0opc7UQc7aYbCv1g7EaiOT', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='hAWviaOpJuJMWvEBkAiF7ZjKRp8pX7gw96IX4VihKF4S4rAeSdut993yPnzAUrzu8bD0ZNvTkQTb54eQkwdhMYtPgqk9Xmmkyu01o3zwHnfXuR0h9KuEvCsZJo0hpoqeVUyfGl9i1zByEx9rjRPCRYydbrKjuy2bzBAJJL8pTtVpSpxXgqqHdGwSSgSMX0z81FodUMGk9xDHDuNr2vZKm9qhsU1lcvoViPLtjkh3Or7UEZGypAvrVahjv3sgR5uJ', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='hGbgaE3Mc3uz2ZV72wGzGZ2ECe4RbhVWZhEfvIn5FhapbTVzck6pZ2kdp1fwCw00OlofkIZyEucFvkQdEBpZcsEqlMaY0YN0qEyRQT4cS4PqS0i87Tke3sy6kKRyWKAGx125Rpvk5kC0PFt0qCRbjB6tvIrhJ7utPdYklyHxGLHLPeVC0gQ2WATI1AJqYkqGuikZWDWnvijNAuc8UTXhFT7CPpI9dVrCQNXLBBsBtN2bMeOZLoazdgYAMkqUXS80', editable=False, max_length=256),
        ),
    ]
