# Generated by Django 2.0.5 on 2018-07-05 04:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0010_auto_20180705_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('c53f5923-4d1c-4d9e-bbf1-c707870b6def'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\xc4\x9d\xa3\x1b\xbb6\xdc\xacy\xf8\xa9\x05]$\xf5h\x11\x03\xa2\x0ci!i\x995\xe5\xae\x1e\xce\x92y\xceHJ,\xf9\xabF`\xfaiu%^\xba\xb57\x84i\xb6\x1d\xb5\x8fE\x02\x1e\xc7\xe2\x00`\xe8"\xb1\xd9L\xed\xa5\xc87x\\HcVV\xd6\x06y\x0f\xef\xbc\xfe71\xaa\x81w\xf4\xb1\xf5\xeeW\xe4\xe2\xa0v\x8cK?\xd6dz\x00#,`\xf0/\x11[?\xc3\'~\xba\xb9\x8f\xdf\xfc\xa2\x13\x94\x96\x8c;\xe8\xbb\x16', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('fddbe8c2-b4b6-4fc8-a23c-c7f639d4ef5b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='BV2dSUB9YN1Ic4W4FagqH4RIi1jFxkZ2xti82PzvBEtdWDpByMFqg4Cu93UpulP3PFrmTbkcDU2L3YYp7KrDsyMWQ8vttyXFmQ6bjzcLGvTBbB7a1Al5uFZkYLepO04lIL0PrzLcUCHypJQKyEXTC0jJm0rGJV6UKqS1k4vlcQjwiPOHbgJUYaLqGtCWXBLNmkJv1RLaPmMw4VZG01jclugNmnzdLOHSgUjKtAnuyDwqec7e5L7gKDXBPudre4SN', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='iqv7c2dhuFDku034b3We7wfOU1XhENIo6nAoNvNlRDotb3gzc2fyNS89QGlF3BFr5MwKon191CaA0CJxoRQOOPg6dX0UqDGsNecAHO2kmIBv5WUnSWAb2j6bStA4s0yNq2BopZ9LgKiDjx2Qm83ZMiovz82hiROiHWYrfRBNZu1XbnOaiHpJENXWEglJkbzYCdLgFROYvKeG4vHqjOTFsZG3vNFDNZOBCHqv69SbFaFzkGDEgooV6W5D6oLy385e', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='8RtubgFoGwWysCEvPEGZ8PCNyvsKWF9IIfrgtJd0hAZboyAp77ZcXw8CLxlAp3cBOK1Lr9On9YAvbP4nA2h49E19s7vukRzimruUJxLNpJMKvIUkNuvUtBrbragDtoRcKJGNbrL0FPrpi2rFX2PpeQe4VSpUH4vFkYtamPMLZGQcA3ONC5g2zi63WGt0XdUSTYa8i1xJPv7fkG5wtf5KXaTJbu5UJeYLIdGNO9PC8E0Fj9QUJoQFa0YQJHHxAAVT', editable=False, max_length=256),
        ),
    ]
