# Generated by Django 2.0.5 on 2018-07-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0011_auto_20180711_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='1ROkmEfIlhNSyLQpLMoTdAdrd2W4qaMo', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='Tk6EcjLVqLy77guV6qRv4W4uBBjYVqyUd15u9LVrMQnYapJa7JFnjrJnI0efaE6IiRu18DAI5GvWNqtjA7Xgs1nvohi5ALUFotT0iZMXsg9kpNylsmsOe0ERqJOasVoltcO0i6tMlb7zZuN8hQ9ZWAmAxm3a5YaBO0V3JZJtVQhb9IFAh9TgeyAb60dn4y6FqnJxGNioexSD4jhPtQmOsANvJv4mJp4EEi52085eWkTshpRlI36ra1ABsJ2jStmn', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='DtdJgjwV0Np847UDpd8rLb2jCiYHzNx0kO9WSdylGi6cbKPj5INjj0GFEnzwTjbzzbkzKySQVJJsnEZ9p0HqP9Zz1MM9qJJPIc07T8ptHKb1jWb0bAMgPvnYqIG85gCdFXxLKs5XsLmkG3Hyym58sylCxWetQmWoJyI9EYk0iSfBDgnY6nvwZnLF9jK9zpoFxCWHOvc9qqgrILp8tDogthPK2Z1JTZWShCMSkQHFa8NhevcfMjBePoKhBJrZC4yg', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='wyUrXRlp0f6uOqQlYHOZv1EVQLs4fwhp', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='nQnU1gmrLdbyVkvTEnnV6dqZm27sfwvK', max_length=32),
        ),
    ]
