# Generated by Django 2.0.5 on 2018-07-05 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0011_auto_20180705_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('c19cdaf9-791b-413b-b94d-43c17a2f44a6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'gR\xec\xb4\xa0\x05G>n(dE\x0c\xd3\xf4\x811L\xe2w\xf6N\x97\x88{\x1b\x9f\xc1\x85\x7f\xbe\xb5\xc6Z5\x88e\xc5(\x01\x87\xc5\x81WHP\x08]\xf1\rKq\x8c7\xc0q\xf9\x8e+\xc3\x1a\x9e\x16xv\xa7h\xd0q\xbc\xad\xd8\xff\xc7\xd2\x9f\xb6d\xd7\xb5\xb0\x1c\x9b\xae\xb7\xaf\xa7\xaaEbD> 2\xcf\x02\xa1pw\x04c\xe9w\xc23M\x01L}\x07_v2\xe4\x7f;\xf6\x13\xdb\x08\xcb\xba\xc0!\xe5i\xbb\x1c', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('d26cd0aa-2db5-4ef6-aca0-a8fecf6f9304'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='ELhBYFY7HwIS9zm9PcRMFlepHbEnFbnLPCsJvrZ9k3r7sgmi9agtqpv5CqvHtjbxVx2Leh4Q81VmTAZQysiRD3flbEqepmLbuZC4ugnQbSRtSDe8RoiPm98oy3wLmmOvfVvyF3x6Z3STaHQztx7jqF5iCfTfCWx8l0hIK5xUYboAc9YS5JYJeAsEM4a7wYlgRYOGG4R9wzs7OJk263II7x91OIdcivb2unKnJEFISFCKRAUR721B1x0YuuhOxE27', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='yES1EstxucNXnsDyzfbCcYQjzkW3vRyKqRF9BgeLOmk95p17CKbOQQIHvrOac7JS5EyrytfZE6h2GmHzCyjEFHvOe6rFQA5fRjNbQ7oX5YNOncS9aRbwGxegaKZnBc7i1J5N2DoNzl9TFoMf41chN7vvvZ7q0vcSvaxyGGId6aYWeNIbI4VmOSS01eaq5cu13p59RsVTapKbDfbxQ9ibo29ELS5ACyFQVzbygWz0FKhnhhhMW0ibbgtmmdTRMyzP', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='SD883qWp39zP6hpwc8qJk3Jn1gKAHkOy5pAn5bcd8tOYPTtx3I08pgzRsoXHtTNBIXWJRb0egMf549ni54ah1LGyEB5fY7Z2chShhe2mQZKr9aGGa5Li5nwV4kl9zGweCoBECEkwtDWUegTdEeXTz3iwOxvNUaEsOuLdKvrxUszwRV3W2Zd2XYBn2kSCnLulYlVP6B8Fp8Qe9Qe6qN6FtIGLwRJkvqtNW9FxDKN2GpH3Nm0gIuTW2iVbVA4pOeVi', editable=False, max_length=256),
        ),
    ]
