# Generated by Django 2.0.5 on 2018-07-04 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0011_auto_20180704_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doornfclistmodel',
            name='door_nfc_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.DoorNfcTagModel'),
        ),
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcDoorGroup'),
        ),
        migrations.AlterField(
            model_name='nfcdoorgroup',
            name='listOfAlldoorGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcMasterListOfAllDoorGroups'),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='listOfKeys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcListOfKeys'),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='masterListOfKeys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcMasterListOfKeys'),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='listOfDoorGroups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcDoorGroup'),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='listOfDoors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcListOfDoors'),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='listOfKeys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcListOfKeys'),
        ),
        migrations.AlterField(
            model_name='profilefeeditem',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
