# Generated by Django 2.0.5 on 2018-07-05 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0012_auto_20180705_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('19ca1f28-373f-4d3d-9d24-5bd560569697'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b"\xf2\xb1W\xcfw)W\xa3\x95\xd6\xf1L\xc1q\xc2\x923<\xc1I\xd6_\x08\xc34\x86.\xaba\xb0w\x81 *\x1et\xcd\xd4}H\x95\xb54\x8a5\x03\xca\xcf\x01\xd5\xd7#\x89\xf08\xfb*\xaa\xab\xbe\\\xb41iR\xb7\x97\xc4\x04AO\xe3u\xff\xc407\xa95\xf5\x9cc\x92\xc6\x9a\xf4\xeb\xed\xff\xb5+(1~O\xff\xed\xd0\xbb\x93\x0fJ\xd0\xd4\xad\x92\xabDMH\xff^C\xf3[\xf1&\xe3\xf9\x8a\xc5\x9b\xc0\x84'\xceW\x0e", max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('749d5c4f-2246-444f-9369-bf9c09a4c665'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='NvdCYX9CFAimg13ynJlpFEmWYNtFNIczkpQhTabZQITnZI1XX9RmcQogaz06SeJgKxmr7QGT1eke9s6nBMsEaR7BD6y094X48LQL9dliVHYeCJzJPijIewsU1Iz6p0XZYezUbjgkS1ATD4K1cfAAN1l5JdHCi0xYrDvBLakACsWvF60DnlaZ1ypP1T7NWv2jkneSg83Z1QZv7b8rlpfwnd58FXDtVAbPXXSo612iMRMBFZSfHoqilKtshNAfgAiW', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='PWY6gk180oF9ICr2EEf1dAiu3JVbNhBkapFeDwqiNQvkwFDilTvJCDXGAAyrhWskht6bwpMe6Ljpku22PUjBGREWMal7gFcL4FTeDVf6VfPWD1p79RdOA6D2haPMc9OTIjYK6nZl0QQvejdssBpSAZs0VytczbKTNXoMLY6Jfb9qvMIevcSficSzMVUDZGUFPKrPqtaYXoiQNgiOj2LKFIANZYo529HSWdQn1jmzdIeZELiGLHoDhreGseLdi1MZ', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='qnKiBbyfi4qXtCIbezrUf4ieOgoP19twdNB2B1huc58BUQpbUfTH3vJlKjtRmct072PvxCUV5glso5E9BsYnAfZenr14BenYft0Bslyxix9kFODWxFbwWCoPcQMjFIQlanMciZCwIkP5wpwb3UJ1jLcG5duYXlS40vnQ9NHzG8KSklNW8d4KQggDziYmghmjOgkSS1ZInLMHjHjsGQvAR1bPkzb5dx2mKOQjrNV3AptU3en8tR9tBQWVxecLZREX', editable=False, max_length=256),
        ),
    ]
