# Generated by Django 2.0.5 on 2018-07-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0012_auto_20180704_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfclistofdoors',
            name='listOfDoors',
        ),
    ]
