# Generated by Django 2.0.5 on 2018-07-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0013_remove_nfclistofdoors_listofdoors'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfclistofdoors',
            name='listOfDoors',
            field=models.ManyToManyField(related_name='listOfDoors_NfcListOfDoors', to='profiles_api.NfcDoor'),
        ),
    ]
