# Generated by Django 2.0.5 on 2018-07-05 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0013_auto_20180705_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfckey',
            name='masterListOfKeys',
        ),
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('cdf00070-03ea-4c6b-adde-7e6758e15205'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'a\x9b\x1c.\xc1\x9b\x91O\x08\x05\xfbW5\x8b\xd6w\x96m\x8bva\xf8/\xd3\x03-\x02\x00=F\x1bQ2{|mm{/6\x8aA+\x05\xbf\xf0\xcf\x9a\x99\x07`\xdc\xbc\xfbL\xb8\xf4\xba\xd3\r|%-\x1b\xc9\xc9A\xe7\xa3\x1e\xe1\x83[\xe0\x87\r\xee\x1eb\xf9\xfdi\x8a\x1a*\x87\x06~\xa4(&LM\xbb^\xebJs\x06I\xaf\x93\x88\xa8\xafZ\xbb\xb8\xab\xe1F\xc2\x00\xf6r3o)\xb4@\xdf?\xca\xdfH!\x97Y', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('a6f02c97-f1f1-4c31-8dc7-88068f137706'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='iYH0IdBgoopnJ4cLLSkMoWFfvBVhXPm4hu6XjU2eUkVpUxv5jSsOR1JSDPHJnPPtLS0JKMV30HFi976iTP96YpqABlUpp1I6ZKBvp6Ndz12tWgA9c0qXqshbmduMk4rjf1zYpt5jeDcg8IZsFzWZzOHOutmzFG8HDNJbCjsXpD5a9JEwVWo18uuG8pd3JMJ1QpkDWSgpcWurB4c328Z1MoeILXGF3hrAId3s0FhpJRfb8Uj2SJ4j9GqelBif18XM', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='Gh5yFXwEiXH56DfrtYX0oBhr8a02q3nXf2mVdCLj7eau9SeNerHilGOY69EuL8gS2gDsUkfRgQtf7zKaMot0zO0OgZHt8UE6vcnpECsAZI26oNPEWUz5C72ZVRr3LAi5IhdNklZdWA3C4IXJTyA7B4u02ueeboeqYwNLoN8fD6vGz2O3xDfcufJwsmkSm7SbEaJtBvSZdLxQmfuv9Sm1QaboN74z5M3QPmkXSjEGsPdSOwiFx4kSFe95qGMmAvZW', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='TrH27cbZgTeGn7GTtyHTTicnYlnKD1qUyGx8j4Qp6Ve61BvB7m5636msSkh6j5YhbU8enSdXgwPgJf1gh4X7zMhEBWnUUTJ9oyM3XPMXvzqlVmE8ar5UuUj3G8XLUe69mwowqwtj5BIayJ88cRwWpMGSEVuonBIy7k6Tp4tB7YFWqoKughS1seb8ZigFQ8EhSDcdqEaAiuRdgxpdufYU9aWKpCIoOXAaYl5f0utQdDaqIr32JOzlhxwfyt2b4kq2', editable=False, max_length=256),
        ),
    ]
