# Generated by Django 2.0.5 on 2018-07-05 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0014_auto_20180705_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('a37145c1-ac0f-4282-9dfe-73f0aa0d5a24'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\x0cm\xdb\x0e\xbcl\xd0}Q\xf2U\xc8}\xc6\xe5\xa9\x95L\t\x81\xd9\x9f\xa0\x01\xe73\x082\xe1i\xd1,J\xf7\xb9\x9c\x16\xfbhL\xd2M\xce5\x87\xe1\xf0\xfei\x98\xa3\xa1\x0cz:\xd5\x9b\xfd\xcf)\xc8\xd3\x14Y\xaaLQ\xf3Ay\x13\xd3\x88\xe9\x0b|EK\x1e\x0056\x1e\x13\xa6M0\xb6rSe\x9e\x95\x05\x1a\x0c\xef\xb3C{y5\x8f)\n\x9a\x1f\x1d\x8f\x7f\x0b\x90\x13\xe8\x1ee\x86C\xe4!\xc9\xfbc\xbe\xe2,\x97\xfd', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('a0ff5ab2-eb35-417b-b61c-288bb1a271db'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='gC2COgx2AFGeRgq3sc99G2rRLIwFH4BeglYuuKX9QCz3DzhrIgb6g5vZf6VAHh44y9FVPRPWWL64m0bfEElDmkGNuXFtcsT9K7ZyvLSrPOmzkFMTlqLtUY9dZ0mfw6Fl1UgwFpApcoR9Fd1jjiwtRUbfGfYV0dik7vEqkTCQszlCuNOL84PQ5Z6m4QMEu9PSNw9Hsfd3Uyx6KuBtxBHK173CEUToSCaCiNQto9CI2fbdXHbsID5M8qoqg5wKYvIj', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='02T6Tz6KQleyFPTYebTLwMxet3x73yrJnXKHc7Y0Bvs7mZOOgYGAVJJ0WwQGZ14YJlbw3w8l8LnM2ELoC4jdiwHidCAFDXUi7hlK5pjXhutGqXsNSZuO0I4g4r3G6GZp4rQtFmwmGHSzAPL9KZzqKeAlyUJilH8z6NOFQlobuOxrAWCryvTlV26Ki8wRoLXZpnABXm9CXRwoJleNHSQBZJknMHpIVHBy7QyWIAVkNjzeRzm1WVhUn3kHGIVPYMuL', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='xcIotrN2Jz4LivrzCekDAB7fRtmcj31Uf1FHqcZvtyzpS9WhOkzj0EBbojUJx1XjCNjZCVml8M4a8cGrZjWIBxITqabusaXjoXdcNoiCzJ5G3t0BafeaoVhAEyOEOp8dUHVWo5azPzeXp3LXKNHuYYkvIG6stz1nBAz6CUR1LJ9nvbf3aD33F8XAm3p07HzxI7LnQLkDs5eYKFIJ2A9K0Zts3F6TgkJJRjA480wQYWLujvp5Iz3KvTdCiZsSHPUj', editable=False, max_length=256),
        ),
    ]
