# Generated by Django 2.0.5 on 2018-07-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0014_nfclistofdoors_listofdoors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfcdoor',
            name='doorGroup',
        ),
        migrations.RemoveField(
            model_name='nfcdoorgroup',
            name='listOfAlldoorGroup',
        ),
        migrations.AddField(
            model_name='nfcdoorgroup',
            name='listOfDoors',
            field=models.ManyToManyField(related_name='listOfDoors_NfcDoorGroup', to='profiles_api.NfcDoor'),
        ),
    ]
