# Generated by Django 2.0.5 on 2018-07-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0015_auto_20180704_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\x18\xeb;\x85\xcc\x84\x01\xb0[\xa4\xfd\xfe%x{c\x8fK;:\xd9\xcf\xdf\xe6E\x94:U\xeeY\xec\xc0\xa7\\\t\xd6\xbe\x9b 9\x9c;h\x9a\xa95\xccL\xcb\xf7\xc1\xadS\xf6\x00\x7fG\x83)Gmj\x04\xd9\x15\x9c\x86/\xfc^\xce\xe7\x985\xeb\x96Kh.\xb2\xcb\x1d8\xea\xbb\x7fC6\xf1\x81\xb8\xf7\xf5\xddh\xeevR\xe4\xd7F\xb2\xae\xa0p\xb1NX\xe6As1\xd2/X*\xb7fp\xfa*\r\xa45\x9c\x81\x92U', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='VCdP3G1JkYBVtW1ht69IwtnrTqGbGWy0R0jnVvHfxZjrK4FMMf0gVRUSvf1RimMV0uFaML1z5zg3FIesABxAwjbVAWJh72p7OEVyVxqxkdTPdo51VYmsB29b39RSWj2LfHjLXxLF0eUw1XcTzOdJg9ZuEpbPYq10ZNQX5wLTWrstaGeLv1sxKTsefb9bRWa2Ngk8wtigTi5lIVShLXA0eagRj2aXpqmAveSpxlSV9n1xm28affzKzTBtfTElmxWn', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='etXNNLdKFyZiRKZMxm3JgPAJpMSBUTegQrFVXg7VIF7YBC8aZA9JcqWjtdH0QfeWKLoFlbApz0YifP4DYbj8W3bUYrn7dI7sRsIdq0uCHkI8sqgERM6GRv4wcloTxNnaRlQMEIeruGg4sfZv4WijTacBScibIs1Si6WGp7GO079TzuSADNGKkgCAJi0fNdpyNKxGuHlwJiuz8Ltb5fe8gFgKETozwXJCL6LyRsBM65dlAiNdxW4y1cwaCjfBogOn', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='Y8nkNqErtTdJ87E4NdXQ1I9ewpItA4MbCpkRZK7VC1EA5AETay6yfY16zlzJf5mFD2ocwt8sFP2HPQxxvbflOvKQnJSHV5C2EZxV4PhfQhlKlljoiZMMskdk7kYF7gdjszJzYA3zbxf7V7JPkMSbLbrmCpeUF1GTCIvvVY7zase0DaTF948kGWEQsQkhwRz4OwQHCMIvnPakCvbMhqI3qntrTgIYlhxzFGwZy2iBzNacuKuzUHYUJmpFo08Foi4z', editable=False, max_length=256),
        ),
    ]
