# Generated by Django 2.0.5 on 2018-07-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0015_auto_20180712_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='PvZ8wPBpB9tajXHhrPz0CjDOiOzNeXQQ', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='PrbdNitPIbTXOT978ub3kTFFJZZMNg2XuhxHGtWCmTi8MwJxVngGvKzp173vozgkZGpiTvmWIpwMd2l1TnewiUcPFs1NNdRweOailnNzFQbk0KCtotwUV0ESYfMU1TkVsHEehAPO4LH3kRQQD4B0BND1llc5CYZ4lfZUZbt8DUUVNtql4EiCQJ5wXhBQeTNzDBSuGsnIO4H7cbB6mxO9E373cKJfMHvW0Equja96HRSDIvTmLNyvEJf6MxdkBQTR', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='dAkcXYBN2jNdXJaAvRv9VGnvXzy29yTwWE17cgQtaiylvZy0DlnK43914FTb5kBCr2kUMrN3e87o84L1BbhMVRKPlaVUGzOs1ASN50WBeULLJ7mUyGrEyGEz7h7ACyN0ucQxUFUW6Gk1xLWftlfPF9HYh9Tq4QgYZDK6llLaryK7gQIL79nJdDuwdXZkKaCoeg2i1RIL2UDFzPZQDeC4EAO2rPrEBC34CrHO00t4cm59zlRYNef0AOAvQ58fOyj7', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='IauMznyByDXW3c0hqm775l19WyN0b611', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='Lm1maY7M3ISksZe1aEkPgwtBmRUTx3r3', max_length=32),
        ),
    ]
