# Generated by Django 2.0.5 on 2018-07-05 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0015_auto_20180705_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('68cd1bd7-6c2c-4908-a0ed-32a2b6a53e41'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\xe4m\xab\x0c\xb3\x9fP\xfc\xd9g\xc1\xf9/4\xb6\x80\xfa\xb97x\xb8\xba\x06\rna\x89\x0bt\xd9\x9e\x9er\xd5\xa8\x9eP<\xc43\x83OC4\x05\xa7\xca\xd9\x05G\x93f^\xa6\x98\xd0P\xf1\xbb%i\xe0>\x0e\\\x07\xe1\xe4\x02k\x0et1g\xa6\xe4\x15\x91vf\xa6\xf7\xa9\x13\xfa\x89\xac\xe4\xe3f,?4\xfa\x11\xd9\xfb;f\xed8\xec+^\x06\xd8$\xc5<g\xb9\x87\x985\xbb7\xaeP&U4uH6\xcc\xa70a', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('c761935e-03ce-4acd-96d1-e07ce62159bc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='6br0nanKEZpvizvq2FMsd2WqxYBba6cimMo9WQ6Vjg8dkAVOL4lIFftbT5DaeSScCRr6i6MtfXBp23Pw2eYtzvwcrbNQVcf6q3rBgBLGiLAL731ohLBRTcjqoP286kDrfwHs4arLw194NLlByILvZKyEO8WMeBoUCRc9npPqqBI3mEsfqUw86HLQ8Ty4kMKPNUhVqvV2KYbmNcdUk5m2jbN3BtZlRdoDZir3TWZIMYMsZ5UA2xX8YzQkd1Nllqoi', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='MQxrOOFmRsW5mabpilnXA2Ibb4FvrzXG8FvPmu14xWZSnnRm1h5Y0JV4Vb7gPEfrImFrarbbnhPOWz7AQ0wjJ0Os28sTMp6kjSdaBEdZzeBbBgLDP3x6v5mF6yripCowK6yqQoXYpEZNRfLuawFuzUgibtSQbL2gKfezpIevAcP8bmGSovIuGnlsUfGgLMgefmyuBGqPGATCifsey3CMEbgm3UUkxdQgoTnImfHnq5NaDpvCgE40b3scJc1X7s82', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='DvcpoAm9tTvy1NEVNI0BcWrTmvBJbznBLsrUJMUjki74td9BaHgfCDSBiKHoZpbUoSCnHSRUY8SBn1Lr5iwN3xyu8QlQnwKcNkyeGXmbceTszhbwDfucaLv6o4f1KwasqEtffKIbPYl2i8FONpvPtW8pS6QoitQCGou8C0bUOY8RoRlULKkc1tSIdUPYjHHhx7QnL90K1f7RiG0DlYfLDPLoYxdZclSJ2wLadD8tS6ynkOoaeNYjVJktctzDf5zA', editable=False, max_length=256),
        ),
    ]
