# Generated by Django 2.0.5 on 2018-07-05 06:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0016_auto_20180705_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('5893a171-ec7f-41cf-85d3-acc22987729c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\x99\xe9vM\xe8x\x12\xdd\x90\x0cc\x10V\x9b\x9e\xe4@\x95\xa6\x81\xc1\x0b[\xa1\xe9Rtt\xbay\x0ew{\x83\xa7\xd7\xae~\xbcv\x9d\x9d$E0\x13\xc97%\x15\x93\x98\xcd\x1aU\x92])W?\xd0\x93|6\xa3\x82\x99Z\x07=\xd2\xb3Q8\x9eK\xbeLIqk\n\xc9\x078\xa8>sk+\x9e\x89\xb0\xe0\x93k\x02\x0b\xcc5=\x8e\xa6\xa3q\xb7\xe2B\xb0\x1b\x8d\xfe\x13\x9d\x85\x01\x03|\x16\xe0\xc9\xaf\x9aA\x9a:W0', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('e5451652-917f-4287-973b-eee98c631de9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='rEAA2RsZw7Kf7eTn3j9vYFs9EdE93MFWW8IWlYjnRl4nQ4AJ6ALNpbtXtc5nsf9iv3qhZwoiZRqTiHahyYUitdLk5krbYHH4FYZmYekDCFkWsiOW28yXZsKUzMNKLJ1XAy85ly13sfy59uFJbZL3i0pHzBdfGeJ8nIXtMYiYaxD7j7lOp32WSEJ3IbcbABfUfDJT4tJzIOEeipysHpIC4str8wA11C80hDvlJRwRHVWqVZtH5AutqPEoj1AtXGGy', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='sYr1dQHDQJY1Y1CLSgjyUZp81J3Tf6Q6poRvkf0aaMOp1a2DTOG3Z3EmGpsp6ScW7uKw232AvMue3VCDRaB34ria8KzbgaJswJPcy3wmmFlvDyMOil1EwanIgCqEMnr2hPl4RQ4GCJLseAd7Eoi3AJHmytCfUsl2uZguURy3aTKOK3CJBVY2hW8mdLjb0KkAyXr2FRKfB7SY5wPVKLPsZ9DrSd87HMYZSeoZoeqvcaOMR55OsyJGPnJkkY92chIw', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='XtAz6y8xqSeCdEpEirQz9wZgSR9Ed0LNQU4XFRwALSpXpbHnstzRN8KDutWbNOyB1gxBzTfbtzwer28MGF8U7MCZSCFet7ZlwOW6O2G5Jdf1DgJQBPTAR77tCw7US8X3oWI3esatkMCHe62LXK1BmT87XLTRn4EjLFGt1xiFCKGYUl6Y0gJCBGpj0SN2x2dQimV77aAPhpjUeBqom9JWTLNLVd2DweYxXyK3dG9RtzeBUKp0bSolwmsDS7oo7gjW', editable=False, max_length=256),
        ),
    ]
