# Generated by Django 2.0.5 on 2018-07-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0016_auto_20180712_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='135UCpbFHmWHt07U0va7IvjhH0PcHW88', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='9aPoeVdSKEAGj68WkKVkLGz54Y1zExR4JPSiQUKNoaZgVeAiiv85okWbSLYPuceVfcR1UuBgkBpVdvHkn71PgL52GnJg3VST7dixFYvkGqYraBX6slcGY0lp41TtViLLmT44CjQjTj2ObkKCU8fKK8btb210yoG5XPxs61cYxseC4vDqeSldUUgonKafi8oc81thlowvF8Vr9sQZd9uYgNnE8X3fjB4IN4cWS9DsOxoW9sbyF7czaVN2y2DimuZi', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='6oTCQK4WJmBfNmDBiMjyZuKU94j9XLrIra3CjBR8zlRxdANzK3NQSXX5R5ocWKQlFscGpdF5rmPDUB0fAQGU5dqnwg8DiERZxnSln9pMw0ccwNZ8FLCjXg9aUNlhYxdMxdBMGnksMNYSYza93vRhH5WuvfIF3CBv7yMHHIcApYUYPyNDkJzljiXKWCDtcvZ1cD1M2qwTy0SojY5FVBhxFzK7ptGX7GtNVKXOGsqMIWqyQ7ixvacxYbf5KPC3iefr', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='iLOfJUgHOysRllSTUa3GyHBI8SWUshrG', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='0RQ2T2DAUDVZ0SVuUAg8wMyF3RO4uYDG', max_length=32),
        ),
    ]
