# Generated by Django 2.0.5 on 2018-07-05 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0017_auto_20180705_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('859f6504-4c4e-48f6-b311-865de358e402'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\x8f\x9b\'5.\x1d\x18:["F\xb5\t\xbf6W\x93I\xea\xd1\x91\x94I\x96r\x0e\xacK\x9b(\xb4\t\x16\x03\xb8\xa7\x01\x88\xdb\xdf\xa8_s\xb9\x1eh(\xf8\xe5\x9cnc\xadv\xcc>xY\xdb\xfa+s%\xd2W-s#\n\xe9\xe1\\\xf5\xb5\xd7\xac~\x99r\x9b\xaf?\x0b\x81p\x1e\x06\xa0\xca\xb5\xc5\xbc\x8d\x97\xfc\x9e\x12\xcev\x14`?Z\x15\x82>O\xed\xb9aqTW\xa5\xcc\xf1h->\x84#\x97Ua\x90\xb2\xf3\x12', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('77086e56-03eb-45c7-a591-7ae6afcd43f9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='wPKwR8vAziUsYfKgiw4Iu1YNxBQSCXsYjZ3C084wVvLxpYyFiGEPJvGPc3YsXdvbuIxu1CosIwMplIcBe494GmFYwihOQnzY8493YYIzmdZ6TQRE4QX378CNLgx4sLKW0eBx7b7iXvjxFXTMK4l1TK8W91on4cpJzRq19llILmstFSzEaLpFPcKAthN3BfkNszvdrq1nfRLKyjkdv2yqfiWGoBaIM9iizOlv6XRd1ieQFnj8ii9ZT0dxTERUbpnb', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='MMwcstX7ccO1By4VnRKGAzsDEz2y0xBaQ3q2njLf7NyKjHbnHhQwPC8jp37O9tQ2dxuGujrYpiyI4L0iT48sqUe8lsANV0JyqTuUwTe9uMnMuq3ld5Hmu4tluCHzHidIAyrrKWeIfVzy4i4iCbqUJsNpL36bKU5yoLQ5DeDfPRKNiW5lAR9cmIvK5HTaFxL3AnXILxre9E8l64r0LrlzCkguBdj6Cvj5DJyiJuAmWm7FLGg4bs0xDJ7OGJTGZWwY', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='D4AU2BIqINa1pOkATJ5aVThPlA17xZqcoivzDV09dhNyyOxnIYSFG8mzMPju2B1hMs52LviLD73smqVtFZXaL9U7rYsAVhh3lZxA2MCw0mTsxMscdmW5UjtmbBNlr82wPFJ6U9Dppfnx6QuawVAMTVOM92dAkZnw7UD9pB2iwoL2XZJuV6kjVgovuKxhyNkx8qaI6xeCTnM2fn3v94TKFJDktdFtwTOBkOt5qyHVI3n0prs923jzLmQe8sWNDZaS', editable=False, max_length=256),
        ),
    ]
