# Generated by Django 2.0.5 on 2018-07-05 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0018_auto_20180705_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('97d5e6b3-39c1-494a-bade-34707ba9da7b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b"\x15\xfb>\x1c\x97\x1f\xd4\x06\xc91\x81\x14h\xe7\x1c\xd0\xf2\xb7F1++\x8f\xd0\xfa\nQ\xd6\xab\t|\xc7Z\xb9\xee9\x99\xb9\xd43@SAx\x01\xfd\xf1\xee,;\x1c\x1b\xec\n7\xa3\xda\xab\xbe?\x81\xed\xb7\x8a\xcc\xb3\x04\x9f%MQuy\xfdtP\x1a#\x00\xc4wG\xe5O\xecgi \xa3c\xdd\xff]\xb5\x1c\xef\xaa\x87Vw'\x91\xe4;\xb3\x00\xd0j\xaey\x87X\x83~\x17\xb3\x88\x01\xcfh\x91Y>\x0f\x97\x06X<", max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('22a8f384-d51a-46fd-95b5-76fd1c817000'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='JS42kfvvjPxTuJcEveL5ZpodZDEaQ9pOeQxoZVlFp0w339EU0zWusmqxCCp87g1XsD6PsviBxbB8BhTUZXKlSdZ18alEu0PMiJK2jscZYyxUMC77AoE8rqd6JnuFZdV6igUEVXGh2Wtlhpe2w4BnxHiZoM0cTKh1tu93yPLhYt5EULTRNcgY6H2n7EpmzfvVjEX1uL75f9AqIg1Nr8F0dz2cUTSb7h1kUTCxl27cHldyew51MkOJlbkGWpE6Sw2y', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='6dF9YfWzDmBmduTc9iu5KEySYmbBD1nQqE6eC7hVFiNMouFf7md8N66eg8BLWPmftbW3NnbSAOoj6yGVUgh2j1kwctbzK3ou6B7xedsAQMwPHDlFTMxMUrmfu9ryATkvcg5cc4AdRTWAzSBf7BiczV23DlzxFM91IAiEsXOGmb7rhTYLqDPZxAe1UStv8odSZ9xvdUd4P8BQ6RWS8q8oOJ00eOD5EwCFBYYYsf48C0zA4UAhspJ6No6qQ7eOOD4D', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='nOhIlhX6PrnAFSHv9VCgyier1nx7aXFB36L7dpXMBRRvX9wXky80Fpediz3D2Vzkw7UGiYZVs7vO87b5cbEZuD594v6EQQI05nA3QLGIpRmMdhr2UiYLsgyuvYYsZmIKSD4cU2iHHue9QpSLlgIQuhZePErXzzljAAWnGf4YqJI1nGaaCrey2v7HZiWNTuUZomTFaU45VCwCv47JJZAUlwcaudb4xwnLSDbUV0yx6YfPytQrqdNeT4waTLsz8VmM', editable=False, max_length=256),
        ),
    ]
