# Generated by Django 2.0.5 on 2018-07-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0018_auto_20180714_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.TextField(default='tgs63yvjEbtOZSgVFcsrX0Y3jW4Y2HIr', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='accesTrue',
            field=models.TextField(default='HwpIEwmCvO2ugxylr1GOkBfwFil5O9EuMLll5mgOoNkwiCr5wV8oWuduRoqXUiKmLbDNsI927j0dqZkoHMAFYYA6ttSUvTJfantOpphqRAdiBSAHFbBMiH7Fr5mP2xW7NHdPxsVR7iI6j14d5lCHUuAglJ8bHGjoBlg3FAWIwyXHHW4BfAt7JG0elFRd4qJNAE1q7p4JsbF65M1F7WQCOuxfWMsLAT6kSkeja9J4MLhcCEF0tj5yjyzo9AaHiiO8', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='WoygzBAZglB2apulowEnuQShyBcOKAR8x0Yxz1qqNTX7PES1zMYlKY7xtX33p4hZE4QMO7B3nz8Umz5gpOtnO9gA2O0hPfLz8UdWncJJzgdc0vdf3H8H1M25lzG7eIS8oSfIcCvifGmhIMsChEj7qViMOqm7GDvazrgADBgAjyt4H4jYdpSYN2A17UFZ1ZDbIyK8rimQuxgwMmPzaFYeggOFOXZNmUDTn5supEEwldYdUZoTxzOLiKSMjTVzR50k', max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='rVt4Np15rsEalRv1OAsFIsLPXISSzLUN', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionSalt',
            field=models.TextField(default='EnjbC87jHK6AIKXWkbebyXYl8MYIV7Cx', max_length=32),
        ),
    ]
