# Generated by Django 2.0.5 on 2018-07-05 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0019_auto_20180705_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('69efb632-9f26-429d-91f0-f866e318ce92'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\xf9.\x00[$qQ\xc5S.\xd4\xfb\x07\xc1\x88\xec\xe9(g\x8e\x82\xb9\x96\x0b\x9e\xa3B\x0cFz\x86\x88k\x94\x8f\x84\x94\xcb~N\x99?\x0f\xd5\xa4\xd0g3g\xcf\xb0\xf7\x93\x9aO!\xd4\x1a\xd3\xb0\xecM\xaf~\xe9i\xd9\x15\xbbi:\xfd\xaf\x94\xf9\xab\x92\xa6\x82J\xd2\x8d\xc5\xa0R\xb3Y\xd2\xa2\x13\x9f/\x08\x15i|\xf8\x7f\xd4\xe2\xe5%ce\xef\xe4\x8a\xfff\x95\xc4 \x19\x1e2\x9c\x95\xd6\xbe\xd0\xc0\xf9\xf6bX\x10\x90<', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('ac63a1ac-175f-459b-a0c4-acd249edf1f3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='ueaJI8oYgu1VlawwRZRBI0lpHfd4lCmehdt4LDQkpj2MWDtg9gDuPC1UUVYo3RU14RtgkrLq6CNnBFOBX4uGt3YFNXYvD2ekjs9y6nDDvBJyb83367B0SofjBq7rZxd7HAaaLHo2LE1T3C0xk7DgdlQa3aukTjqDyJrGTAYW5c0e28uZV5Wefh0R7zBGETSPpsS5ZumoJkR4Ac2iN3ZmY8rsdxaSljkLs11brnkdj3KKUvqIbCpYLXZ8WytjevXa', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='qnZDsWRc3mAJmHi2BIWwH0dtJhpj8KSgx8so4ZMI9dCBbNyLizxffN2B1mnfGZIunMoWcvE6MJycGd3Em8D8yIALlfP7PmPw4CPvktXKpoIh5KwTEy7bm9DX3afMvRjZNLXBZ93ceolSeNRasBjA5RRuNhFu56jJU24x9BoyzAoJRbTpRXYf9kAmPuCXE7BVstyKggHMNUTB6dj5YxcRxxcBe6OK4yj5BtrAhqFXcYzARHH4zdjdjHV7no7QJWvl', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='sIp4wOAzTpzTceVb8NupesfiK3enfznsWWngYgGYjqW9gi9jnjOqhYsor8YEAyeOjgx15Sl6vUhQ4vYiaX6gHtA62cikNivP2j9rH29HE6meNXHA6ehEPWWuDa9OnMZL7J6yI7IaWMh7ljm2TE2Bdq0MYDqpmnmtNwUxn5jhPZOgTu8XaG3AqzKng13S6FCuYxBgJseBS24XxMBZZLne5qIVWoh4NsPmdXYuvDlnXyNyHXH4Wr58x2PiNun8JFdE', editable=False, max_length=256),
        ),
    ]
