# Generated by Django 2.0.5 on 2018-07-05 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0021_auto_20180705_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('0d130a0a-d8e7-49c5-966a-c3326d570714'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b"m\x14\x89\xc6E\xe7tD[z\xbe\xa6\xea2g\xf6\x92F\x16`5\xfff\xac$\x9b\xcdAK\x14'\xd4G\xcb_f\x81\x8dDG;uee'\x08\xbd\xf5d\\/\xb6\xad{\x04\x88\x10\x11\xf2\xb1\x81*J\xe0\xbb\x83D\xda\xf8E\xb7(:\xec_<\xfd\xfb\xd4\x959X8tm\x95\xe3\xcdD\xbf\r\x9f\xec^\xad\x9ch\x95\x04\xb8\xd1\xe5K2\xc1Env\xcd\x08Pq\x8eXA\x18\xf7\xd8\xf8\xb7\xbfb\xc0\xfd\xa3\xa0\xdc1", max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('a71d2c87-ecd3-44d3-a852-315a77643f82'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='p1eumJJqJcCV2a2z5JDfvwlRCygA3PGOTFpyj5eqt2N5FnU1kyW1Sho6fjjVA7999BdQ6q3u9YHNxBUxwyYF0rfrnoxw51f32wHoavnEXDHQWw7je2wC5OyFsVWTpNA1uA09PGVAlFowhdrOLUu9mwbCiaCNRbT4oFRYdLL1NFfaGld6XiyhClU8nPscJ4dcGvMDajPq2MnWrT45nBBY3lQzMmCL2fBQMQMWPzBAHC2nrlwysAGeRxcJmrTdE9ED', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='8Z9IFAcYfAaTCPNth3M6DKyihc9U9B6UgTNKq8eiyvNyBsad3LhB3TGCJKSenuw00MfiuxexVZpMpzjfQFejkRZ9FCDzamjMi1wYcu0AbA6FeJr4FopbLwRpgYKeAU5cNLy0CcjsWwx6vJUfFmzgEE29WUevxKAjBuXFefJPAd9k10jh6J486WyLbGVd3Nx9cz1z7aMnsCHg8MUSqNusRTDyqBhOUIrRvpGBigCw8lBToEy5NNGfrznwK3rGECQs', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='AKgpjgUwMUV1KXW4Azq5W1HQ3eqpuNwkbie8wKgksuCzZc0zyQqhJIOrlaCRuiA9qkV1UsKfCTqNNUvWIxjpSJHA5rsvfljBfO1W7OiNRFKkVU4ewNPRyRbB2fLWrSB1JczdldyRSz7fF3MgHPa46GTCa0CZiLVpEWyvLneygHpQrOaauf7gRLE7D8BvD5f1yXjzrknkdgVRAiUIX5fV7YkT5MINU6wo6EwzgBDUqMM5oTNn4tJqQXMTgg26nkKx', editable=False, max_length=256),
        ),
    ]
