# Generated by Django 2.0.5 on 2018-07-05 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0022_auto_20180705_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('c8ddaf17-910a-47dd-b482-e34c502e373f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'h\x87\nt\xd2X\xcc\xf3\x1e\xe2_\x94|\xdc\xf8\x01\xbb)\x1c\xb4\x02\x12o\x9c`\x80\x01\x00\x82\xea\xdb\xa6O\x19\xfd5k\xb8\x1c\x9a\xdf\x9eo\xd5p8\x15\x01\xbeL9\x12\xda\xda\x9a\xbeJcb\xa8<zXd\xc2l\xdbaV[8\xc9nv\xfa\x02o\xeb\t\x9d\x0f9\x94\x1c\xa2\x17\x19\x958\x98\xef\xf2B\x92\xc3\xfd\xc6bwm\xa3\xa1\x0e\xbaa,-\x9f\x1a\n\x9a\x18\xba\xf5\xda\x18J%\xf8\x83\xb2\x9c\xa6\xc6\xbe\x933\\', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('42200ca8-b599-49d8-a7b6-8765e3511101'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='UWRI6lMZ7YlhXs3FPy1TUjG0mfixRqNpFhKYwsgKts7lz8ONHY39tNadMgiCFG6zK0kjQz5xUWoAXFguSAn934kXCOrePPqMmZwermKOHcvwp5v1QDf7PFZyp1swkXW996xi2sqvEK5QwBKNZnR3TlcEmgm2YDdUrceNZndIYe6jtRwwStsDQd7d7J0BUz0Q6vGZDWMYGvIbPO9oMaIimQbz1OhSs7wLThJtsldaCJ4RJpCBcUHHku9BWGb3rL26', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='M5byNXpMDYj00YRPBQOd6ngJ2QMM3cjHpmtDCtIFyta0RtdK4XmNymeguCbrqgpZDOOrXQzhCCPpDg59h88bg70XROsxXsHdyVJfNsPbJoh7eURXgtc8O7VrdPsBNSwHKGJmn1vd56LCYBHvycaZEYGRnUKx2KRK2NpTiKFAuiS0igwMcS0bsP6VMiJAoWtmOeZs1lf1PXeOCUqcaE33174kxOmxQgeIt4laZLtzn5mXwftD6aDwGiVVP3kqEp1t', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='R8Xj78RE2bRu8PYZK0u3djWA4knFVl8LFcnAWISFDizi78I7Kc9cU9O7AA51zNVxQubsqdNJfgVWO0eipMNFS5BP5s5Nyjvu4O24xakDeIZ584guUy1DlLs0Fg3w1xseAQ7ojEAEb4pT6TKzyH2ZS7TDlBJQw6caGvtjYgiJklQc4P3wIvUyn5ym9I0N2HH13RMOlAPyiYBGlIACe3W27bPfW2dJq1uhgwUhboho5GLBOilELCF6ICJXX4Ej09wr', editable=False, max_length=256),
        ),
    ]
