# Generated by Django 2.0.5 on 2018-07-05 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0024_auto_20180705_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('6d3c4faf-107c-4e23-84c6-dbb271039bcd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b"\xb6\xab/5G6g\xd8\xadk\xfd\xff\x92\n\xe2:\x14{PMy\x9d\x11\xff{\xcf\x17N\x80\xc1\x1b\x8a\x03\x95\xf6@\xd2{\x19\x806\x87\xd2v\x8f:\xdf\x9ajeU\x9b\xc7\xe9\x05hF\xcam\xa3\xb4\xff\xdf;\x9coV\xaa\xf2_\n\xebRC\x06\x13\x86\\\x08\x0c]a\x90'T\x86\tb2\xe4:\x94X\xba\x0c\x97T\xdb\x81\xb7\xd4\x82\xbd0\xc6\xde\xe1rf9\x94<f\x89\xed\xe1\x08G\xcb\xb3\x84\xb6-i\x1d8\x07H", max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('cf098221-d5b6-4cd7-aa4c-b3aae094a86c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='BBO6eeHLamTEJdG2OZonOL4Lk9NIskzSXjQ3DSHFYVu3Joz8JSP7V23bH3wrarJ2FKMEhGGDaVgBrlorVX2HxYUdYE0mjtWWVSvbHz1uVBWGrgCdW7YMxIDXPV2BR5UFWZrimVBSLWDjVxhn88cgkRqVCXrNoqS2C0d9fpg81ByIqoatFdInzoWWCbihzhw71XVmwYAW34vkWdt37mcoP2exnj1Q3Q6DI0YJ5DRIDJCqAevnE92gDz3Jnfz9JAuK', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='98rn64lYx05j33LD3u3aBnG5cp9ooneaBwaYJQ7JwXAs4hvUD8NoGw7uXnXuqYTV7hr5MIaqfjRC0cPtOIhplq64vfUr7icwfrXVsSEO9OXXymMRPxu0Ua7FdfGkwqInyf2f47xJxKATSoZwnNx19HhDQLLkTOT3uwduyyCJXYRW1xJjVJTAlYQzHJc3MHoigapvOt6Zrt0mDeiAcEE6VuaGHeU7QZIiy8dZ7xdFr9cXuIsJXORhXL7WExX1O0Jx', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='lyR52qNBKp5Bc623oFvbW0PfvAd183JEDfUuwqQIl2RAORLH8i3OUrDVs7q1lBT6mDzG1k90h6EaYYgYZumWuScgMdmIdnQ6KplCPJCg4gs7aW8ju45WJ6aMl0Eq3S4tghunW3dT2LAE36myDs8UShhlD8E3LwvynUgWRWPnAstKHtFJhZrycpuXWFNCQwGCGLYDUvZDnkP6TeBMkuWxzPk0eAkRFJh56YQR2drXzHGxIrgXMKOt9hRaLqgbEpPo', editable=False, max_length=256),
        ),
    ]
