# Generated by Django 2.0.5 on 2018-07-05 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0025_auto_20180705_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('4317a2dd-1813-4480-9ce0-74420b6157d4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b"\x04T\xbe\x1d\x02\xe0;g\xca\x9c\x08\x89\xc8\t=\x81\xb5\x91\xab\x82\x7f\xef\xbf\xc9=\x8a,\n\xf0l|\x1c1\x8d\x05\xe1\xd8\xda\x9a\xb0d\x8ea2\xed6\xe6U\x98\x02\xcfD\xd0\xfc\x0cx\xec]>\x8fh'\xb9\xe6\xd6\x10\xf2\x83M\x01\xb6\x8e\xe8\xda\xd3u\rS\xb4b\x90\x00\x81\x96&F\xe0\xb1\xef\xb6\x0c\x0b\xbb\x08\xff\xf3\x85\xfcI\x06\x94\xea_-\xd4\x9d+\\R\x05\xa2\xb8T\xbeJr\x8cu\xd3\x16\x1d\xb8>\x1b\x05\xcf\x90\x1b", max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('89a52fc8-f40b-42e7-8c9a-54e71bb81435'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='qhDodahKMWkMUlnDR4ebQXkZXwnkwF9fIU2ZaJ7j6TeAJcdrJpdrOH0U93JInOXAX6B8A7ADnIC642rKJ0PU7Iyv3vhi56ojyxjGEqGyemdV9EjgAivjDACrX88wypQfVejirI7lhTJM3NUlswheTrGhutKHdXvIFKZDGkXFjM06K1ftRzSkUxps9PCEbblpJwuaMH5hu4M4hfWfAjshTgtIdXsYLQpc6H8b0bauv6x7qha1DZR6ssGjpAQUQHkt', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='hP5ZxLAh7UiB11pO0zN4DRaMANVeUlApWAyjvDJcqSM3guOgaU44ya48QZynku9osYLoX5FiXu8G5w3YZOzIpL9M1nkIHAQf8HBtrMtNvWa0fZY6UgzLHVf5S4I90uivyge2XOLPmuVFV0IJIVxjti5rbFVy9fsmDj3TWDM3Z0Xb7Zzr3tQgxDxOPUwr5rWU607VOLucrMEyBGCoZe0G8zKmmscTzEpYdl3FrpKjX2NDRLADRinXfA1YSpl9m5W9', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='vxog7PGp0sT19fuYFSmMX7z4DrxJMCYiie12NmmxhwGWf8Js4CZRj5QL4iEdXdHvZtKL0hjkIcicm0HZGiyj95SFs1pOGw69Cuq8e3Y4f25rdr0df61vhgc80uo5HH4RUluaglXSWyY45af5Qlt5FkM6DCNjztcFkjM7ydrHdzMsYBZPyLPdMa74TwUAY4Q2nXMdOB0gWp3iJhNgtLsYH1JHuiD2fKxtH1xuKKZL2xDJhKzteRuvWYhhEtofUNDI', editable=False, max_length=256),
        ),
    ]
