# Generated by Django 2.0.5 on 2018-07-05 07:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0026_auto_20180705_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('e789fbbe-4292-4ca4-b3e6-aa771abd99ef'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'[c\xa7h\xf9\x8c\xd6\xc6\xdfe\x00a\xe2\x08\r\x07\x7f\xb5\xfa>\xb4h\xfe\x80A\xf1\xb14Ee4\x16y\x13\x86\x9d=g\xe0+\x96\xa6\xfd\x1f"\xea\x05-c\x14\xfd\xb6\xdf\x808t\xa7\x9a\xc8#\xe3$5)\xd7\x9d;\xdc\xcd\x89\xde-\xb3X-\xfa2>[6X\x01\x9d#\xa1\\\x1fh\x9d\xcf\x02\xc3\x035\x94\xf7^\xd4\xaa}\x9f}\x8a\xe5\xe3rAw\xf7a\xa5\xf4i\xd4\xcdT\xb17G\x93\x10>\xbe\x1e\x0e\xe6?\xf7', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('da813e26-5554-40e2-a6dd-68b5dac887eb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='MrDDuud5nAgfrTxG1xv2Mwb1JvezaOAqjVgxyy9auya5NywTDRv86El6ze7Hl91NRM3mh7HHTeSMlaEsOzgGJjLUeK7PcE8nFOIYNnFrL52EaLXbA9DdK2QsoNYBrTMRi3HNNL68piqUoaw4z85fSfBzMtp6IToadcxUS8VE1ggJc5UUh0MdfTUEuT94pevkuvXnekHxbMwMqJUwta1Iz38kE1WQaUz9bmkWwOsIre3Uh0YICqD7pgtgvh6NxGzJ', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='8UdcOI2kUk4f7LCpmFgYQEDBlo5EAOZxbxjWL1JM3jHBqgrM4059czgadLTePrqeYCKhnfGM2ZIwiJ9g7v2HnQJY8UiEINNZ8DEnc6yPQ2mtdsvWbk0Rfchh2masldUacMifJuQH8SUWqzK7c2JfNVdv35li0T04xPY0qrKBCGxds2Y6RpseIurfHv5acbXRLzySbCVDInNjcY1tmDX1bUrEroJI4IJpESHAJU3a6yg2OoxDHa6HvzjZI54zPnKh', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='0197SX9EqcQHb2Nh9dvpjKN9ckwSVnztMSPA1rZONd9LlRTL5nGdwvBwVzQbnPR3gLqoQimnmwhMvbZjcnLj8SaecccNIbdcbo0XemovbdLUu9MBFDWJVGHWBpbIFkUi54RoTewwasnBx0xvuHvtlEzlxYuVi0m5HSmPCOCSDAeeZA0KrZ25oQ9spNxBG5t0vBUD07sish7VbEvCSiSTabyQb1iiX4cNbhjF0pHgBecgKF26fEMKWIDWYifqt0DY', editable=False, max_length=256),
        ),
    ]
