# Generated by Django 2.0.5 on 2018-07-05 10:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0027_auto_20180705_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfckey',
            name='keyNAme',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfckey',
            name='masterListOfKeys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles_api.NfcMasterListOfKeys'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfclistofusers',
            name='masterListOfKeys',
            field=models.ManyToManyField(related_name='ListOfKeys_NfcListOfUsers', to='profiles_api.NfcMasterListOfKeys'),
        ),
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('9f648a6c-e537-439e-a414-95e02ee7ca15'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b"\xa4\x83?R\xbb\xa0\xc1\x88\x071\xcf\xect\xcc\xa3|\x18\xbd\x15t\xd4\xbd\xae\x00\xa6\x12P-e\x99<9\xc9u\x9e\xd2d\xff\x0e\xf8\xb8\xc2\x0b\xe3\xa5\xe1\xdf\xcb\x84\x894\xb2a\xe1\x0c4\x9d\x00'\xdf_U\x14\x8c\x8d\xdel\x8e\x9d\xfb\xbe\x80\xb8\x0b2u\xdfX'\x0c\x91\x80\xa8\x9b\x83\xf9\x01%K\xbf\xdf\x01\xc8\x8e\x03x\xdc\xe2\x90\xdf`\xb8\x8f\x9d\xda\xac\x8f\x8f\xaf\xeac\x0e\x01\rh\xec2Vt\xb8\x0b\x19\x80)!A\xb8\xbc", max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('09983007-d138-4078-bcde-a9194c1f6ea6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='pst5exmc4WZioYAw6EEc1jtQmGgDrFegQ4lw1729m4yUIwwbBh5Z9fwidD3YgFbTgrcLXda5W84jVqkTP4pA6AxcqWmtKJNKEnRz1BpHuN5DNAgAvVSZDEZGmJlIBgwzIx31PcH5Xb5hEF1ys1syZrskXNzW4QAkncC6Qq6QjPz99F1WxHEUsX4cbwm5hi54OouWSW3HgRDx7znKLDrVRbAh7YxJmEwuVHohglcleFBMbgZ9zyZvDbtvMubfV2G8', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='tvtCuOPoEsZwSlot8qlSmC3JPw0ut31I49itBkDk7CUsjZ3f69uO5POYCDh15pI1c7g11wEBELit1s8TC3Qrehfc5WaMxfaVRf7BJWKDofM3xJFx8VDgeJOcLElgw8iY5TVYBBXWAYZf5zeDUWtembJmRy3ROBptGkarV8lP712xKbrQxpxcx0mzVrubhqdkwh72jYpZFGjC0co4gPm14KWbyl3eLIa1KbCX1PpmMXjVLFrCTvE2LmJfRtB4Q5TM', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='RNmuzkobmmNXkN3KRAlj37hKq2PpTdKEVjUbXHeV6a6sGlfpdRAHLjdXVjVP4H7w6AjNDAiqqOxoxVHvOWcmSwvVsNS1PMhUtpnj3XCEWCFsg970eBH7tZeMFwu0GD6l4B6we98yHTaohlOiUjy3gx3C8lRkiVWqib0ln6JwcnUaIkHx1R4NBDXxNuK6INp0Y0z5XAB97A2sI5kHu32Tb5q0SR19EjsUv0tojLlyR8yvGFY1eciU3yR1hz23rqNZ', editable=False, max_length=256),
        ),
    ]
