# Generated by Django 2.0.5 on 2018-07-05 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0028_auto_20180705_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('de84f5cd-a21f-4583-9564-1babccbb2f79'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\x1c%P\x9b\x13\xf3\xfa\xc4\x01\xa8\xecP\xbb\x95\x80\r\x8b\xee6\x02\xdc\x12.@\xd0O(\x11\xb2\xd5=\x1f\xaa\x90\xd5\xfd\x1a18w\x19\x84\xd8\x1fXV\xd7\xbaZ\xe1|\xdcEs\x05J\x0b\xaer\xdf\xd2Ok\x0c\xcf4<\x0bB\xefk\xaa\x84@y\x08S\xb8\xf3\x07Q\xb1\x88\xe9\r|\x04\xfb6\x1a\xee\x8f\xd4rm\xb7_\x11\x1b\x883\x16^#Z\xab>\x0b\x07\xc5q\xe3\x856B\xad\xa1`\x02\x9b<\x1a\x0e\xa0\x8c\xb0\xc8m', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('11c54c05-545a-472e-b350-cfafe45af00f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='S0gmsQdxFSXmLBeAFKT9XJAk5E83SKwjAuH7hfFzDpryM1kISC8nkrL1m4gQOvw2GnPEA4vgGyxH6DMLbAgYqMtV68E4XPZh3az3kTE5pz31IwV7uGy1ey2REVJNfdy8xXZW06fKVOBrQKpm59nrqW9B1h0kAUVu5m7iWzqAWCiOWZjbeKAdR0ujV7O3JUNshz99wgnyeKRy5HMHOhN5dbAEPDE0qyeclZa2l8JBJN8nFOVuISYLPGY4ORI4kN6D', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='Bqql8kI7X8Y4xPZRputY6dCxKB23jEMEGc9PBQPgbWzIrNgYrThAdVeanLa2FsevfNWhNhjxRD0ClHIg5FAhOX1iXFtnGWBT0fMBnl84BkKjCYgDq7deUGgqLcRXljI1aCiJUlqQtQsWk9NQXmNAr6ImFQpBK2Z9iwbO8MExdUMxnv5v403lWVWyvNSlSZnyGb62kSoxcOCtavZ5CKwf51mq1OJM2idEBIjuVTvyqHwuO96D24HfxyyfQ5E4kQj0', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='yM3zRSplq7sU52qWyEmHA7C7XR8jM4AYSpWxstKSBeL9AhlGEwLGxvKjZLqZUURskPYqJc5pAFXcK2nTwbjbUTjesl04G5mnYCLpyQ8xy876XeGffsT9mlFO2t9wTtjeQhyGtDQET53BsPzvLaGgyXf1SpgbuS3mQNm8oIgZqAknVCaafZptuZDU3QdxX4caeeZd6z8yJLqP1fPfl9EnNGsYR5UZacV3VQvE0UMJCRg2GBMMEcmJdinBPg6xRINc', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='masterListOfKeys',
            field=models.ManyToManyField(related_name='ListOfKeys_NfcListOfUsers', to='profiles_api.NfcKey'),
        ),
    ]
