# Generated by Django 2.0.5 on 2018-07-05 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0029_auto_20180705_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfckey',
            old_name='keyNAme',
            new_name='keyName',
        ),
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('f3067fa1-3a79-4ec4-a581-353057478b34'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b"\xd9\x90\xfb]\x05F\xa9\xda\x7f\x87\xba\x0e\xcc\xf4\x86\xf7\xb78\xbeon\xe8\x82\xaa\xffW\xcc\xf5\x05k\x02\xaf\xfaMr\x7f\xb6|Y7\xde\xe2/\xa9 ?M\xdf\xd8\x08\x11'\xc6\xdch\xe6}hMn[\xa7W`\xbe\xe1PFu.\x1b\r\x80\x85\x88\xc8\xd6\xd8\xb7\x154U+k(,86\xfe\x19\x8b\xad\x03\x17R\xe8\x88'\x99\x1dW@c\xe6\xbb\xdc5\xac\x18\x14&5\x99G\xacLO#\x06\xa50y\xa0=\xd2\x0f+m", max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('64e58393-ba5b-4de5-bb0f-88ff6c81ddf0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='rXjVpvICoGF5PjI1w3ty1vFueA79fFAL7H5CcqduZGKkaBjbd6T0g5DNDnAIeJ0LEzvADHJAT9tdh5LBGq1TTJa7giwUlKsUnpWE8EzSN6uRhK9K1tVKhbjGemxQem8nvyrX7RGSMXKe4l9wRg5nb8ayALr88S6lSJBMJfGJugS7ErWZfYGf8WxiW3W3DCrIluSOsbSqNFkctMl3dvXS8AezCYCQanWz7GbiHrbZLDi9HUYu2iUYku1Sa2E6jje8', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='sLmv7G941aV4xP2Q72tCrhepoPVSC2rD65sDQm3XW8f9MZSG8ltEY7eYdcsMT0ezBBM7yBQEa5bj7d3hABVCbh23TQnEM1QUl4nxDrePN7KtJQMUxZ60mZxqApxzPKyl7SaNKD9WwTSBLmstOajKrHbtTczQEd3HTHIQVroqFTMnaBXZx7WJksl079M2KKauSA1YIrAMPotUXlnocHjLohTpNDaeOJ1nvy6aJCiB0iQKjEOGMoaQGl6GUh1FNQAd', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='SvXkAnXdGOrFvqZPKfqYvJUQ7lltY6B9fCOiXQ7D3qQQAo2UA4YSnvICYc5S2WBkAyjBYg9ExXcPqmPzErHsaEeupJcRmn6tg1l3VWbEG2oj2DrF3VHNZbQmibdJni3WTu9ZLjfeoOwzo0P22kn3OXIVYzcSpqSzGO9ZSQGwo10mRvuJqVrCh2Nlw7eQM9RChY4kdLq91COjlA5wg5mUZtZTalmrjHxW25TOy8ZCsacm9j7eriWWSACSZLXFl3gs', editable=False, max_length=256),
        ),
    ]
