# Generated by Django 2.0.5 on 2018-07-05 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0030_auto_20180705_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('80eedfbc-bc21-497b-850b-7a3e01c7fad6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'II\x99p\x95\xa2\xe9\xb7\x80\x18\xe7\xb3\xab\x11Ng\xf1\xb9\xad\xd5\x8b\xa0\x80\'\xf2\xd3\xbc\xe8K\x16g\x85\x97X\xb6m\x0e\xd3\x1de\xb4\xc8\x99:N\xc0\x08\xc4\x0c\xa5\xe8\xe6A\x14Wa\x10\xc9T?3"\xb6\xc8\xee\xb6\xb7>\x86"Bb\xdf\xef\x17\x08\xeat\x05\xdbU\x0c\'\xda\xd4NA\xca\xd42\x10\xe0\xc7_E\xfeU\x80O$\xe5\xae\xeeQ|\x07\xe5\xc6\xf1\xc6\xa4x\xf0;\x1a\xe9\x8d\x8a\x855\xed\xc5Y\x0e\xd1\xe7\xf9\x06', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('3dff460d-c66e-4791-bde4-2d37520a7bb4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='zRz0ui4VO5MXgmQSMxWgXWSAmFISvwHrqOycIrEnPjlowl8BkHJmwIdPWQFJIIhuPr4YS8721uYsS5wM97cd7LrLr9yqQxlnLKUZo2xztlRC2KKtDYllHoLvcRPcxbvTFLKsErfKwGib1Ra7VFUViv7Rzs2fLV8xNjQH5ExRFFN2fe5IarGdbgCDL6EguaquaiCrgLaY2SgHT8DJZYPIR7MVa8fPQnbifKcf7b7wGSf1wCC0U3lAAftW1jzOMJvi', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='gOqk9dG5vlMsJSXHOEyxYZhDj0tDOvw67AXajqcibcZiqLvcTDvkoKppsYu1MnkyetmYsoXYuYyZlnHF5tjSMXjWD9PE2RklUngHo54O7m678srjoY9z5FKCnIJOdSxM5vhyUX6xzzptvpkMPqVBdyqwtArFmIE2aYcs9HRJHotgyvUZJhENQ2bwkqKTxcrZwHJdxGSy387VWoGDHZmXeUW1qCffitYO6gX4CaSzkCv2GqxHc34az64mMxAPzRmE', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='qM6S8yTS0eYG3mG7EGqF6zaFEwSYKtVSfGuP5GsVnH0xnXkC1KFnY32sAcWY24t5wmsRVUlO8v7QyTJgOoGdODZpEP6BBghXxb7W7fF6ONEUHlU1jviTM9OevqprEnmQ6JT7dEtv7MlWjJfjdMxAcZDldNGFOvt4YEpD6im8WNxJEiB2Ao1hxh3RbXkC4em37TATpB0M5kPMpmXG52hpwPSQ57mnliD9XBEOLHpvC7mQF4OcIUVq5Rt914XfJJYa', editable=False, max_length=256),
        ),
    ]
