# Generated by Django 2.0.5 on 2018-07-05 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0031_auto_20180705_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NfcListOfDoors',
        ),
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.UUID('859f7b26-f676-49a4-9ba2-f19e79c0c4bf'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\t\x08\xa2\xf1\xad\xde\x887H\xdf/\x85\x1aY\xf3\xd3Q\xbe\xeeX\xd4`\xcb4\xccQ\x07\x80\xa8\xb0\xc8\xee\xdb\x99\xe48\xe4\xc2\xbdd5_\x89\'\xacc4\xc3\xd9l\x99jnk\xe3\xd84T_y\x1b.\x1f\xf4y\xd7\xb5+\xd1K\x01"e\xb9\xa7\xcc\xf0\xea\xb3\xd5\x904\x80ws\t \xefe\x99\x15\x1d\x92PVA\x90\x98\xfe7\xc8\x14\xdfG\xf5\xff\x1d\xa0>\x17\xc2yr\x9a\x0c\x8c{\x10\x05\r\x89\xd3\xdc\x00\xf6\xfe\xdbD', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.UUID('5f591b86-4cdb-40f1-905e-e184878945e7'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='aKi7PU9sFeBe9EFRRIMzLXV62wsf5NQ6j9GAWNjqTz7QTnwsTgZDw3WBaLc5j7Hy2oyHG5hLcS457m01gUwY4IVgLKDpOBzAUbEvScYci5793MT79p8zBdopwlAjAMF5k1mpGLi1bEf8cqAvNogprRJkEEV79rVfjw6kYW56gjdJSDnsMjGODBHf7v0WxaQNWqCgVIdL77y7hswRIxunPETTWJHGcJgk0utifozzomCRKRFHLpW8CesSlrVnnm0F', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='3e5ZkmfSuwkpJomJ2Ofl0yLKzyCUCEvNOvXgKOZcrSaEEDV5ZR4hmAlJleQbHgaKwMnIm1L1z3BZVX61FVxMq01UvqTP1MjNjqhnjEeMkeOgztrp8o7y8anJBrxosyUYbjmIQrY2QfplC9SxQG2S3lu5CJmh3RpOwt9VYZ5FWgQ7ZxRUOljmc3zS4ZLeAqWzUWq2m49iVvvZEqi0YOOAVezsnG5lrquBT7Lb9n98ZapEK3NBwpnqYBwraEU8tNWj', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='vppa3uqSTrB1n9fiJDTowwH9Z1AZRUbi9YVoMQjvX1g4YUKx7XIPvKoswHU7W3GfOt6fe9tv5E9jerqKpDHbIfWP41eQarDmqOYG5MvRgLrUVGyzQ6M2tazBARTxDDsAsZENZ0ithtjO7HZN2VVjwdxDEKBOByhAnckW878BBB0et4JhvLGkA9sIk1S1GaGFANCbP9aaBJCNFgypPaDTVJthQCHc35Cf1PwG2FluSPZN2afg3MK3Fjg3hMCEmD5E', editable=False, max_length=256),
        ),
    ]
