# Generated by Django 2.0.5 on 2018-07-05 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0032_auto_20180705_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfckey',
            name='masterListOfKeys',
        ),
        migrations.AlterField(
            model_name='nfcdoor',
            name='doorUUID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'+\xca\xfb\xb0\x1d\x84\xe9\xd8\xd0W\x12\xc8\x81He\xbb\xaa\x18Z\x85\x06\x1a\x89\x90\x13~x"\xb8&\x1b1\xddwV\x9a\x1b\xde\xf0\x9acy\xbb|\xa4\xc7\xdc\xc70n\x04\xce\xe6\xee\xc7\xd2G\xa4F\x05\x976\xe7]\xd5\xe3q\x89\x19c\xc0\x13v\xe0#\xddav\x1f\xe4\xa0\x18\xdf\xf2\xac\xfdu\xefiP\xed@\x94^\xcf\xbd9\x8e\xd5\x0f\xb5\xe7!3?\x80d\x88H\x06\xc3Q\x9ch\x92I\x14\xc8\xc8\xd7\x16\xf2N5\xd1\x81/\xb4', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='keyUUID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='sxFfO5pxxyeSYyJc2dmVDhjv3EHmSLsps8w4Wg5A9kScQWcvOB4TA9PqaHRf1I1VNWce8B0T67wI4Ox4poOVccKbusCfJW5L1cj8T6Vp4sa6KXp1Rr8ITw2AHrVxOzhkRDYd6UXc7X8Gc21N0MpHzKOuTAjrOfLIKMfvXiJLkVB7hZHTiEfYwgw74LrZZnOpKVOluhZ0LneAUi7JHuU7NaziSIhK317fdx7lAMkqNWRzPhaNq56mKzcvgG8L1yga', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='8Vt5ACNBcUUseTlbBFCR1vb5W8rLogR732xtxyxaZceveAS9DGCFK23CbsAOtjTNexvj3ptpLOZUFYqv1jp9dhZONe5w4MlUgxUbKRD9RWkw8PMQMVufUsPxqGwrL9aaWgYY00oB5fHmU1DjhS2RrD7x8oorRwUxwbKtxzFzU5tLROh7sSkcVhgxuyX4mi2W9EkF96IHOZiEiLYh8TbVPR8gh3F5m96trv24NEpoXKKpRL5SR11yGi40bk76Izbz', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='oVfcnXDkyMKwIBuLkWTd7CjDXAIlHVA9kQxgSYa3oOOnVYJ0dBwIIIsc9aPxfIerULP87UXvnSz02RF5KyL9zW8zSxdButHiOG6n7E6pcmxryhUCBk7xx6Jys2IH9E6HHx3FY7fEgxTu38xg46cKRt58E4GFmTHTXMAQ0xq6fCTDmQiQuXfa21hnxcLRWQ74qpgEoysZul7vvygYRZ7mP5LelH1FJw2reqYJV6WNOXSiXNIRiEJtFirEMzOeRiHw', editable=False, max_length=256),
        ),
        migrations.DeleteModel(
            name='NfcMasterListOfKeys',
        ),
    ]
