# Generated by Django 2.0.5 on 2018-07-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0033_auto_20180705_1033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NfcMasterListOfAllDoorGroups',
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\xfe$\xf76s\xcd\xdc\xd9\xb1\xda\xa5\x95\xe8\x0fc\xaf\x9d\xf9\xfc\x94\xb5Q\x0f\x83\xda\x17q\xc4Up\x8d\x95\x8do\x02;I\x88\x8c\x9eb\xfb\x88\xf4\xa7\t\xe3\xc6\xa6\xf3\x8a\xa8r\xf6\xe0R\x17\xdf\xca72\xec"\x111\xcd@\xbfi\x8b<6\xd6\xdc\x02\'9\x9a\xb9K\xd8\x88\xb4E\xb8H\x97\xd9\x04!\x0b\x89\x10\xd47,\xa49\x018#S\xae8R=\x11\xe2\xe7\x9c\xe1\xa5\x7f\xa6\xfc\xdb\xbd\xbc\xdah\xc5\xab\x00\x16Zh\x03\x08', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='WQ2VOSJybx5OHsDatLIa6Bt6OD3VF0HG25LmT75zlJrVXXGWV2km1nSEvfyhOyZLqcK7OLKsnTBCfqzAXpwcSqxzcRtszbBWX42L6oAGkDEQ8t657aq2Thzgaf5ePR66T0E7vbRPKWbzbli08K1ZNbhY6UL2V72ofNIfJnrJAVACv8q7hReTg4ZY4rJEG7j2uEAdwBlaaVInDJr9u8UlHdjnDRcHp0U3MRwBGlz6OhDLaXBOj2sFVFJllvnkV2L6', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='z5hFeW1TmlYHLNN317coXaHzmuKTmspudnwhEGsfbmTC5d5rf0pM7yIX5MQEoq4bS8Ttoo9WgauP5phLqQHJR6UCQUj5p444vzb4fRcj5mLT97V9oRmlIHlF78QiHTjU3LSJYwHZzhgXGndo33Q06BH82PQXvhasSQfvi96Cu3Gxyx6D1XSrNT0XE86MoVVZVs0LEfBqMWD2NUrZFIftgDnEcpOWC79TxD1wZtHAmc64er6RfwSYvOhMfAdbbqMQ', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='saaNWZqRRzE3Jpac77VmGIdElKH9USJ3mFA0qyFFeid5el84L3pcZLSoAhHLdxlby6iLfQjhTqS3JcdE9zYr5upXH3u2u233iQoJ0xZuufKV6EUKILZxGbiHVwh9X4HhCOBtXyrRXC976obZqGLL2XIV6eAZ24dBmaj7H5slFUbTjP9ZSG0VGyEfW3jL9WYIdYGKChq2XmuKgUQifXJZAoBY0irQNd9EGyzj1RP8dxC00Pv9Q5MG1T9uNVHxWiLZ', editable=False, max_length=256),
        ),
    ]
