# Generated by Django 2.0.5 on 2018-07-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0034_auto_20180705_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfckey',
            name='test',
            field=models.CharField(default=b"{B\x1f\x1b\xcc\xc5\xbf\x01{\xc2u\x9c_\xc4\xbd\xc67|~\x00\xd4\xc2\x87\xe2\xa8\xd4\x01<\xa7>\xfd\xc4\x91`G\xadj\xd06$\xad\xbe\x8b\n}Qg\xa5\x86\x0e\xc3\xbel\x1e/7\xbcC\xe4.\xce\xeb'\xe4\xb2\x886c\xb9\xdb\xde6\\B\xb1\x87PT\xa9\xa8r\x9dq_\xbc\xea\xd0~e\xa85\xd5\xa9\x05\x990\xe6r{a\x97\xcc\x9f\xdcB\x1a\xab\xd3\xc8A\xd9\x1c\xd6\xdf/\xdfzi7\xa3\x0f\xee\xa6\x90>\x1aa$", max_length=255),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=b'\x9a\xa6\x81\xf21\x0e#r\xd2\x1c\xea?Opl\x10F[\xafj\xcd\x1f\x8a#\xed\xb3\xc3l\x1d\x90D\xf7\x06\xd4\xd9A\x08vi8,\xc4\xeeu\xf7\xa0\x99\xc1|\x19\xdan\x97\x8b!m\xc1\xe9\x91\xfe\xf6a\xe4\x86\xf8b(\xe1\xdfG\xfc\xa50a}\xe4\xd2i-Y\x8f\r\xfeWh}\xb3bUK\x00\x87\xdd\xffj8\x80\x9c\x8b\x99Gc\x0f\x0c\xd16\x9d\x0e\xee\xf5\x89\xc1X[\xff\xc0\x16yMv3 \xb0 \xf9Vp\xf8', max_length=128),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='w7egGUffZPXG1dj22G822hy86jeIBKAbkBxLUr2emTObolraXm6By0A1IiohXM6dxefp1wVQIjuTmePR9284hkXoaBmEBIbNBxSNYNjZzkcWK8KZF3XgDuomMCIcZiysF0c6wNf3Khm8Ktk4NeDU2M2RHa08exarivnlluGtABEPAOJR16pChI0RYAP5n66MhRk5B8KQJimLYeGUMOMxT1ZB4nIOUwrgxniUi5ua1frQnwGeQ7ClSy4i6SQk0MUa', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='Un0hfOyu2Uxe1eNZcfVHssOGqJNqilEjOuCMrDzzl7QsQCSRl1K8Dnf3uAR8pnTPLaC71DwTZU2QL8xrdCdkHrUuT7zRop5rmsx995BhEZ2MUNFKp4Hjs4ulTrZEaDSYk0GH49F5I0A528EBJEUfb30tPIPhdMXZU2vqSyDcSXNnr6cqekrwYe1wIZNShvB3ouuLfkYAXkO7wfsOHmJ0Uq8y4g2UceKcOkA53g49sYQsoQwX1oq2Klg9IF97mDoe', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='JbADx8RVaNGIkR6j6ajXjEclmwkCbLyjfGhA6hiOBjKwwBgMdm0l1KNHHm3bxZadqnvS9BdS6IvXKA1vwb9vbpTLq7Xq58XSIOH9QmWEPZiEobdih7Qn4XrUruFMexDuKls6fvBTCTRYimpnIeWl17phG4BHntJXHVjJKR9QPl6hCp8D6Kwc8YyyOFvcupSH3eprVrXBda8jAcxW01wB0xiS1Js5TwCEVlMxmRRbissMi6EFjjIZCKlKPViCDpYs', editable=False, max_length=256),
        ),
    ]
