# Generated by Django 2.0.5 on 2018-07-05 10:43

from django.db import migrations, models
import posix
import profiles_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0035_auto_20180705_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfckey',
            name='AESEncryptKey',
            field=models.BinaryField(default=profiles_api.models.NfcKey.unique_rand_AES, max_length=128),
        ),
        migrations.AlterField(
            model_name='nfckey',
            name='test',
            field=models.CharField(default=posix.urandom, max_length=255),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='TDAT',
            field=models.TextField(default='q7JWXSQ94rn3WF9JYVr3miwmnnVXLbfNagZ59DJqbdYijy7LArl1hAjMewgx4icuOOoPRcOibMXGHow4h9cbovv9j0LBQtmOOFaXvr61DKciUNeJhaK5T31Hm4RUy1gahELX8nl3F3nqQCTUAPgd1d2H4743Bf7RiTpjeZftoncVIx0eJoy08veKfHDEhsTuvmZK1uSbLB4RJyCTafOs7tHeajUqbNtkKHbrVCJiXKxgwk5TLvhL8j16QMzV164d', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='accesingUDID',
            field=models.TextField(default='ddxDX9LThKLZC8CllR1ipbfoyGCZBe7KR3lDHpNBYxBwjeykRrJyl5hs4mkSxNNWs1DOsXLS2NgqydSUNWlJm5tf4N7NMwcLGZSHrUEiPQ5vLSu5I8hjs9gqoZ6hWszwYNEEjh6dKUrKbmjB5m1Mzera45wAhXU5yxXdwfdALHlhSCHX9dSjyoPZ6arYnZKZF90aitYGeJXjPxWpHeYfHvkP4LBiQTokmKFpnrIqi3g5CqhR18ywcdWHMZ5gX6SJ', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='nfclistofusers',
            name='encryptionKey',
            field=models.TextField(default='khEfyR6svtNwhssTtD7LkQRlv838Haxla4FMHhiztmUsL479bkLPUGkG2mTx4uCCLuDhKbPFhSf6JgM921ULmTDPUeUh5AoMRcZGpzEA6QxXI8o24ULgj5ozstaC3A9Al6QSeDXqE5ACTSL4O8TUwRirrL6CCCnGbv0PB4rfduqJVwSrWRZrOQHzleuIt3aU5yga1w0WYafiFMgbvIAcZ8wV5TCRGWMoxVd2xZp0P14i1ZwFrPxCtgLwDyK6nAph', editable=False, max_length=256),
        ),
    ]
